import {Navigate,createBrowserRouter} from 'react-router-dom'
import App from './App'
import CadenzaLayout from '../layouts/CadenzaLayout'
import HomePage from '../pages/HomePage'
import DashboardPage from '../pages/DashboardPage'
import LoginPage from '../features/auth/pages/LoginPage'
import OAuthCallbackPage from '../features/auth/pages/OAuthCallbackPage'
import UsersPage from '../features/users/pages/UsersPage'
import RolesPage from '../features/authorization/pages/RolesPage'
import ProfilePage from '../features/users/pages/ProfilePage'
import ProtectedRoute from './router/ProtectedRoute'
import GuestRoute from './router/GuestRoute'
import AuthorizationRoute from './router/AuthorizationRoute'
import {permissions} from '../config/permissions'
import LessonsPage from '../features/lessons/pages/LessonsPage'
import RentalsPage from '../features/rentals/pages/RentalsPage'
import ResourcesPage from '../features/resources/pages/ResourcesPage'
import PaymentsPage from '../features/payments/pages/PaymentsPage'
const protectedPage=(path,element,permission)=>({element:<AuthorizationRoute requiredPermission={permission}/>,children:[{path,element}]})
export const router=createBrowserRouter([{path:'/',element:<App/>,children:[{index:true,element:<GuestRoute><HomePage/></GuestRoute>},{path:'login',element:<GuestRoute><LoginPage/></GuestRoute>},{path:'app',element:<ProtectedRoute><CadenzaLayout/></ProtectedRoute>,children:[{index:true,element:<Navigate to="dashboard" replace/>},{path:'dashboard',element:<DashboardPage/>},{path:'profile',element:<ProfilePage/>},protectedPage('lessons',<LessonsPage/>,permissions.lessons.read),protectedPage('rentals',<RentalsPage/>,permissions.rentals.read),protectedPage('resources',<ResourcesPage/>,permissions.resources.read),protectedPage('payments',<PaymentsPage/>,permissions.payments.read),{element:<AuthorizationRoute requiredPermission={permissions.users.manage}/>,children:[{path:'users',element:<UsersPage/>}]},{element:<AuthorizationRoute requiredPermission={permissions.authorization.manage}/>,children:[{path:'roles',element:<RolesPage/>}]}]},{path:'auth/callback/success',element:<OAuthCallbackPage/>},{path:'auth/callback/failure',element:<OAuthCallbackPage mode="failure"/>},{path:'*',element:<Navigate to="/" replace/>}]}])
