import React from 'react'
import {Navigate,createBrowserRouter} from 'react-router-dom'
import App from './App'
import CadenzaLayout from '../layouts/CadenzaLayout'
import HomePage from '../pages/HomePage'
import DashboardPage from '../pages/DashboardPage'
import LoginPage from '../features/auth/pages/LoginPage'
import LessonsPage from '../features/lessons/pages/LessonsPage'
import LessonSchedulePage from '../features/scheduling/pages/LessonSchedulePage'
import RentalsPage from '../features/rentals/pages/RentalsPage'
import ResourcesPage from '../features/resources/pages/ResourcesPage'
import UsersPage from '../features/users/pages/UsersPage'
import ProtectedRoute from './router/ProtectedRoute'
import GuestRoute from './router/GuestRoute'
export const router=createBrowserRouter([{path:'/',element:<App/>,children:[{index:true,element:<GuestRoute><HomePage/></GuestRoute>},{path:'login',element:<GuestRoute><LoginPage/></GuestRoute>},{path:'app',element:<ProtectedRoute><CadenzaLayout/></ProtectedRoute>,children:[{index:true,element:<Navigate to="dashboard" replace/>},{path:'dashboard',element:<DashboardPage/>},{path:'lessons',element:<LessonsPage/>},{path:'lesson-schedule',element:<LessonSchedulePage/>},{path:'rentals',element:<RentalsPage/>},{path:'resources',element:<ResourcesPage/>},{path:'users',element:<UsersPage/>}]}]}])
