import {BadRequestError,ConflictError,NotFoundError} from '../../../common/errors/appError.js'
import {requireAppId} from '../../../platform/applications/application-scope.js'
import {createPaymentObligation,getObligation} from '../../../platform/payments/payment.service.js'
import * as repository from './rental.repository.js'
const create=async({appId,customerUserId,resourceId,rentalType,scheduledStart,scheduledEnd,totalAmount,requiredDownPayment,currency='PHP'})=>{const owner=requireAppId(appId);if(!Number.isInteger(Number(customerUserId))||Number(customerUserId)<=0)throw new BadRequestError('customerUserId is required.');const resource=await repository.findResource(resourceId,owner);if(!resource)throw new NotFoundError('Resource not found.');const total=Number(totalAmount),down=Number(requiredDownPayment);if(!Number.isFinite(total)||total<=0)throw new BadRequestError('totalAmount must be greater than zero.');if(!Number.isFinite(down)||down<0||down>total)throw new BadRequestError('requiredDownPayment must be between zero and totalAmount.');const start=new Date(scheduledStart),end=new Date(scheduledEnd);if(!(start<end))throw new BadRequestError('scheduledEnd must be after scheduledStart.');return repository.withTransaction(async(tx)=>{if(await repository.findOverlap({appId:owner,resourceId,scheduledStart:start,scheduledEnd:end},tx))throw new ConflictError('Resource is already reserved for an overlapping rental.');const rental=await repository.create({appId:owner,customerUserId:Number(customerUserId),resourceId,rentalType,scheduledStart:start,scheduledEnd:end,totalAmount,requiredDownPayment:down,paymentObligationId:null,status:'PENDING'},tx);const obligation=await createPaymentObligation({appId:owner,referenceType:'CADENZA_RENTAL',referenceId:rental.id,totalAmount,currency,db:tx,metadata:{requiredDownPayment:String(down)}});return repository.attachPaymentObligation(rental.id,obligation.id,tx)})}
const list=({appId})=>repository.list(requireAppId(appId))
const checkout=async({appId,id})=>{const owner=requireAppId(appId);return repository.withTransaction(async(tx)=>{const rental=await repository.findById(id,owner,tx);if(!rental)throw new NotFoundError('Rental not found.');if(rental.status!=='RESERVED')throw new ConflictError('Only reserved rentals can be checked out.');const obligation=await getObligation(rental.paymentObligationId,owner);if(!obligation||Number(obligation.paidAmount)<Number(rental.requiredDownPayment))throw new ConflictError('Required down payment has not been paid.');const result=await repository.checkout(id,owner,tx);if(result.count!==1)throw new ConflictError('Rental is no longer available for checkout.');return repository.findById(id,owner,tx)})}
const returnRental=async({appId,id})=>{const owner=requireAppId(appId);return repository.withTransaction(async(tx)=>{const rental=await repository.findById(id,owner,tx);if(!rental)throw new NotFoundError('Rental not found.');if(rental.status!=='CHECKED_OUT')throw new ConflictError('Only checked-out rentals can be returned.');if(!rental.paymentObligationId)throw new ConflictError('Rental payment obligation is missing.');const obligation=await getObligation(rental.paymentObligationId,owner);if(!obligation||obligation.status!=='PAID')throw new ConflictError('Remaining rental balance must be paid before return.');const result=await repository.returnRental(id,owner,tx);if(result.count!==1)throw new ConflictError('Rental is no longer checked out.');return repository.findById(id,owner,tx)})}
export {create,list,checkout,returnRental}
