import {positiveDecimal,compare} from '../../../platform/money/money.js'
import {BadRequestError,ConflictError,ForbiddenError,NotFoundError} from '../../../common/errors/appError.js'
import {requireAppId} from '../../../platform/applications/application-scope.js'
import {can} from '../../../platform/authorization/authorization.service.js'
import {createPaymentObligation,getObligation} from '../../../platform/payments/payment.service.js'
import * as repository from './rental.repository.js'
import {RENTAL_STATUS} from '../cadenza.constants.js'
const decimalAmount=(value,field)=>{try{return positiveDecimal(value,field)}catch{throw new BadRequestError(`${field} must be greater than zero.`)}}
const create=async({appId,actorId,customerUserId,resourceId,rentalType,scheduledStart,scheduledEnd,totalAmount,requiredDownPayment,currency='PHP'})=>{const owner=requireAppId(appId);if(!Number.isInteger(Number(customerUserId))||Number(customerUserId)<=0)throw new BadRequestError('customerUserId is required.');if(!Number.isInteger(Number(actorId))||Number(actorId)<=0)throw new BadRequestError('Authenticated actor is required.');if(Number(actorId)!==Number(customerUserId)&&!await can({userId:Number(actorId),appId:owner,resource:'cadenza_rentals',action:'manage'}))throw new ForbiddenError('You can only create rentals for another customer with rental management permission.');const resource=await repository.findResource(resourceId,owner);if(!resource)throw new NotFoundError('Resource not found.');const domainResource=rentalType==='INSTRUMENT'?await repository.findInstrumentByResource(resourceId,owner):await repository.findRoomByResource(resourceId,owner);if(!domainResource)throw new NotFoundError(rentalType==='INSTRUMENT'?'Cadenza instrument not found.':'Cadenza room not found.');const expectedType=rentalType==='INSTRUMENT'?'CADENZA_INSTRUMENT':'CADENZA_ROOM';if(resource.type!==expectedType)throw new BadRequestError('Rental type does not match the resource type.');const total=decimalAmount(totalAmount,'totalAmount');let down;try{down=positiveDecimal(requiredDownPayment,'requiredDownPayment')}catch{throw new BadRequestError('requiredDownPayment must be greater than zero and no greater than totalAmount.')}if(compare(down,total)>0)throw new BadRequestError('requiredDownPayment must be greater than zero and no greater than totalAmount.')const start=new Date(scheduledStart),end=new Date(scheduledEnd);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||!(start<end))throw new BadRequestError('scheduledEnd must be after scheduledStart.');return repository.withTransaction(async(tx)=>{await repository.lockResource(resourceId,owner,tx);if(await repository.findOverlap({appId:owner,resourceId,scheduledStart:start,scheduledEnd:end},tx))throw new ConflictError('Resource is already reserved for an overlapping rental.');const rental=await repository.create({appId:owner,customerUserId:Number(customerUserId),resourceId,rentalType,scheduledStart:start,scheduledEnd:end,totalAmount:total,requiredDownPayment:down,paymentObligationId:null,status:RENTAL_STATUS.PENDING},tx);const obligation=await createPaymentObligation({appId:owner,referenceType:'CADENZA_RENTAL',referenceId:rental.id,totalAmount:total,currency,db:tx,metadata:{requiredDownPayment:down.toString()}});return repository.attachPaymentObligation(rental.id,obligation.id,tx)})}
const list=({appId})=>repository.list(requireAppId(appId))
const get=async({appId,id})=>{const value=await repository.findById(id,requireAppId(appId));if(!value)throw new NotFoundError('Rental not found.');return value}
const checkout=async({appId,id})=>{const owner=requireAppId(appId);return repository.withTransaction(async(tx)=>{await repository.lockRental(id,owner,tx);const rental=await repository.findById(id,owner,tx);if(!rental)throw new NotFoundError('Rental not found.');if(rental.status!==RENTAL_STATUS.RESERVED)throw new ConflictError('Only reserved rentals can be checked out.');const obligation=await getObligation(rental.paymentObligationId,owner,tx);if(!obligation||Number(obligation.paidAmount)<Number(rental.requiredDownPayment))throw new ConflictError('Required down payment has not been paid.');const result=await repository.checkout(id,owner,tx);if(result.count!==1)throw new ConflictError('Rental is no longer available for checkout.');return repository.findById(id,owner,tx)})}
const returnRental=async({appId,id})=>{const owner=requireAppId(appId);return repository.withTransaction(async(tx)=>{await repository.lockRental(id,owner,tx);const rental=await repository.findById(id,owner,tx);if(!rental)throw new NotFoundError('Rental not found.');if(rental.status!==RENTAL_STATUS.CHECKED_OUT)throw new ConflictError('Only checked-out rentals can be returned.');if(!rental.paymentObligationId)throw new ConflictError('Rental payment obligation is missing.');const obligation=await getObligation(rental.paymentObligationId,owner,tx);if(!obligation||obligation.status!=='PAID')throw new ConflictError('Remaining rental balance must be paid before return.');const result=await repository.returnRental(id,owner,tx);if(result.count!==1)throw new ConflictError('Rental is no longer checked out.');return repository.findById(id,owner,tx)})}
const cancel=async({appId,id})=>{const owner=requireAppId(appId);return repository.withTransaction(async(tx)=>{await repository.lockRental(id,owner,tx);const result=await repository.cancel(id,owner,tx);if(result.count!==1)throw new ConflictError('Only pending or reserved rentals can be cancelled.');return repository.findById(id,owner,tx)})}
export {create,list,get,checkout,returnRental,cancel}
