import { useMemo, useState } from 'react'
import { Alert, Avatar, Badge, Box, Button, Card, Divider, Group, Select, Stack, Text, Title } from '@mantine/core'
import { useAuthorizationRoles } from '../features/authorization/authorization.queries'
import { useAssignUserRole, useUsers } from '../features/users/users.queries'
import PageHeader from '../components/common/PageHeader'
import LoadingState from '../components/common/LoadingState'

const unwrap = (value) => value?.data ?? value

export default function UsersPage() {
  const [pendingRoles, setPendingRoles] = useState({}); const [selectedUser, setSelectedUser] = useState(null); const [saved, setSaved] = useState(null)
  const usersQuery = useUsers(); const rolesQuery = useAuthorizationRoles(); const assignRole = useAssignUserRole()
  const users = unwrap(usersQuery.data) ?? []; const roles = unwrap(rolesQuery.data) ?? []; const roleById = useMemo(() => new Map(roles.map((role) => [String(role.id), role])), [roles])
  const selectedRoleId = selectedUser ? String(pendingRoles[selectedUser.id] ?? selectedUser.role?.id ?? '') : ''; const selectedRole = roleById.get(selectedRoleId); const error = usersQuery.error ?? rolesQuery.error ?? assignRole.error
  const saveRole = async () => { if (!selectedUser) return; const roleId = pendingRoles[selectedUser.id]; if (!roleId || String(roleId) === String(selectedUser.role?.id ?? '')) return; setSaved(null); try { await assignRole.mutateAsync({ userId: selectedUser.id, roleId }); setPendingRoles((current) => { const next = { ...current }; delete next[selectedUser.id]; return next }); setSaved(selectedUser.id); const updatedUser = users.find((user) => user.id === selectedUser.id); if (updatedUser) setSelectedUser({ ...updatedUser, role: roleById.get(String(roleId)) ?? updatedUser.role }) } catch {} }
  const loading = usersQuery.isLoading || rolesQuery.isLoading
  return <Stack gap="xl">
    <PageHeader eyebrow="Authorization" title="Users" description="Assign users to roles. Effective permissions come from the selected role and all changes are enforced by the Express API." />
    {error && <Alert color="red">{error.message || 'Unable to load or update users.'}</Alert>}
    {loading ? <Card withBorder><LoadingState label="Loading users…" /></Card> : <Group align="flex-start" gap="xl" wrap="wrap">
      <Card withBorder style={{ flex: 1, minWidth: 0 }} p={0}><Box p="md"><Title order={4}>Users</Title><Text size="sm" c="dimmed">{users.length} users returned by the server</Text></Box><Divider />{users.length === 0 ? <Text p="md" c="dimmed">No users found.</Text> : users.map((user) => { const isSelected = selectedUser?.id === user.id; return <Group key={user.id} wrap="nowrap" px="md" py="sm" style={{ borderBottom: '1px solid var(--mantine-color-gray-3)', background: isSelected ? 'var(--mantine-color-blue-0)' : undefined }}><Avatar size="md">{(user.name || user.email || '?').slice(0, 1).toUpperCase()}</Avatar><Box style={{ minWidth: 0, flex: 1 }}><Text size="sm" fw={600} truncate>{user.name || user.email}</Text>{user.name && <Text size="xs" c="dimmed" truncate>{user.email}</Text>}<Text size="xs" c={user.isActive ? 'green' : 'dimmed'}>{user.isActive ? 'Active' : 'Inactive'}</Text></Box><Badge variant="light" visibleFrom="sm">{user.role?.name ?? 'No role'}</Badge><Button size="xs" variant={isSelected ? 'filled' : 'default'} onClick={() => setSelectedUser(user)}>{isSelected ? 'Selected' : 'Manage'}</Button></Group> })}</Card>
      {selectedUser && <Card withBorder w={{ base: '100%', lg: 390 }} p="lg"><Stack gap="lg"><Box><Text size="sm" c="dimmed">User</Text><Title order={4} mt={4} style={{ wordBreak: 'break-word' }}>{selectedUser.name || selectedUser.email}</Title>{selectedUser.name && <Text size="sm" c="dimmed">{selectedUser.email}</Text>}</Box><Select label="Role" placeholder="Select a role" value={selectedRoleId || null} onChange={(value) => setPendingRoles((current) => ({ ...current, [selectedUser.id]: value }))} data={roles.map((role) => ({ value: String(role.id), label: role.name }))} searchable /><Divider /><Group justify="space-between"><Text size="sm" fw={600}>Effective permissions</Text><Badge variant="light">{selectedRole?.permissions?.length ?? 0}</Badge></Group><Stack gap={4}>{(selectedRole?.permissions ?? []).map((entry) => { const permission = entry.permission ?? entry; const moduleKey = permission.module?.key ?? permission.resource ?? 'permission'; return <Text key={permission.id} size="sm" c="dimmed">{moduleKey}:{permission.action}</Text> })}{!selectedRole?.permissions?.length && <Text size="sm" c="dimmed">No permissions granted.</Text>}</Stack><Group justify="flex-end"><Button variant="default" onClick={() => setSelectedUser(null)}>Close</Button><Button disabled={!pendingRoles[selectedUser.id] || String(pendingRoles[selectedUser.id]) === String(selectedUser.role?.id ?? '') || assignRole.isPending} loading={assignRole.isPending} onClick={() => void saveRole()}>Save role</Button></Group>{saved === selectedUser.id && <Alert color="green">Role updated successfully.</Alert>}</Stack></Card>}
    </Group>}
  </Stack>
}
