import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import '@mantine/core/styles.css'
import './styles/globals.css'
import {StrictMode} from 'react'
import {createRoot} from 'react-dom/client'
import {RouterProvider} from 'react-router-dom'
import {AppProviders} from './app/providers'
import {router} from './app/router'
createRoot(document.getElementById('root')).render(<StrictMode><AppProviders><RouterProvider router={router}/></AppProviders></StrictMode>)
