import {positiveDecimal} from '../../../platform/money/money.js'
import {BadRequestError,ConflictError,NotFoundError} from '../../../common/errors/appError.js'
import {requireAppId} from '../../../platform/applications/application-scope.js'
import {getResource} from '../../../features/resources/resource.service.js'
import * as repository from './instrument.repository.js'
const create=async({appId,resourceId,instrumentType,brand,model,serialNumber,rentalRate})=>{const owner=requireAppId(appId);if(!resourceId)throw new BadRequestError('resourceId is required.');const resource=await getResource({id:resourceId,appId:owner});if(resource.type!=='CADENZA_INSTRUMENT')throw new BadRequestError('Resource must have type CADENZA_INSTRUMENT.');let rate;try{rate=positiveDecimal(rentalRate,'rentalRate')}catch{throw new BadRequestError('rentalRate must be greater than zero.')};try{return await repository.create({appId:owner,resourceId,instrumentType,brand:brand||null,model:model||null,serialNumber:serialNumber||null,rentalRate:rate})}catch(e){if(e?.code==='P2002')throw new ConflictError('Instrument resource or serial number is already registered.');throw e}}
const list=({appId})=>repository.list(requireAppId(appId))
const get=async({appId,id})=>{const value=await repository.findById(id,requireAppId(appId));if(!value)throw new NotFoundError('Instrument not found.');return value}
const update=async({appId,id,...data})=>{const owner=requireAppId(appId);const current=await repository.findById(id,owner);if(!current)throw new NotFoundError('Instrument not found.');if(data.rentalRate!==undefined){try{data.rentalRate=positiveDecimal(data.rentalRate,'rentalRate')}catch{throw new BadRequestError('rentalRate must be greater than zero.')}};try{const result=await repository.update(id,owner,data);if(result.count!==1)throw new ConflictError('Instrument was modified or no longer exists.');return repository.findById(id,owner)}catch(e){if(e?.code==='P2002')throw new ConflictError('Serial number is already registered.');throw e}}
export {create,list,get,update}
