import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, AlertDescription } from '../../../components/ui/alert'
import { Badge } from '../../../components/ui/badge'
import { Button } from '../../../components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../../components/ui/dialog'
import { Input } from '../../../components/ui/input'
import { Label } from '../../../components/ui/label'
import { Separator } from '../../../components/ui/separator'
import { Textarea } from '../../../components/ui/textarea'
import SelectField from '../../../components/select-field'
import LoadingState from '../../../components/loading-state'
import { formatCurrency } from '../../../utils/currency'
import { lessonsApi } from '../api/lessons.api'
import { studentsApi } from '../../students/api/students.api'
import { paymentsApi } from '../../payments/api/payments.api'
import { useAuthorization } from '../../authorization/components/AuthorizationProvider'

const unwrap = (r) => r?.data ?? r ?? []
const readBase64 = (file) => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = reject; reader.readAsDataURL(file) })

export default function LessonsPage() {
  const { can } = useAuthorization()
  const client = useQueryClient()
  const canCreate = can('cadenza_lessons:create'), canEnroll = can('cadenza_enrollments:create'), canManage = can('cadenza_lessons:manage')
  const packagesQuery = useQuery({ queryKey: ['cadenza', 'lesson-packages'], queryFn: lessonsApi.listPackages })
  const studentsQuery = useQuery({ queryKey: ['cadenza', 'students'], queryFn: studentsApi.list })
  const enrollmentsQuery = useQuery({ queryKey: ['cadenza', 'enrollments'], queryFn: lessonsApi.listEnrollments })
  const [packageOpen, setPackageOpen] = useState(false), [enrollOpen, setEnrollOpen] = useState(false), [attachmentPackage, setAttachmentPackage] = useState(null), [payment, setPayment] = useState(null), [file, setFile] = useState(null)
  const [form, setForm] = useState({ name: '', description: '', price: '', numberOfSessions: 1 })
  const [enrollForm, setEnrollForm] = useState({ studentId: '', lessonPackageId: '' })
  const create = useMutation({ mutationFn: lessonsApi.createPackage, onSuccess: () => { setPackageOpen(false); client.invalidateQueries({ queryKey: ['cadenza', 'lesson-packages'] }) } })
  const enroll = useMutation({ mutationFn: lessonsApi.enroll, onSuccess: (r) => { setEnrollOpen(false); client.invalidateQueries({ queryKey: ['cadenza', 'enrollments'] }); const v = r?.data ?? r; if (v?.paymentObligationId) setPayment(v) } })
  const attach = useMutation({ mutationFn: async ({ packageId, selectedFile }) => lessonsApi.addAttachment(packageId, { fileName: selectedFile.name, contentBase64: await readBase64(selectedFile), contentType: selectedFile.type || 'application/pdf', type: 'PDF' }), onSuccess: () => { setAttachmentPackage(null); setFile(null); client.invalidateQueries({ queryKey: ['cadenza', 'lesson-packages'] }) } })
  const pay = useMutation({ mutationFn: ({ id, amount }) => paymentsApi.pay(id, { amount: String(amount), currency: 'PHP', method: 'CASH' }), onSuccess: () => { setPayment(null); client.invalidateQueries({ queryKey: ['cadenza', 'enrollments'] }) } })
  const online = useMutation({ mutationFn: ({ id, amount }) => paymentsApi.checkout(id, { amount: String(amount), description: 'Cadenza lesson enrollment' }), onSuccess: (response) => { const value = response?.data ?? response; if (value?.checkoutUrl) window.open(value.checkoutUrl, '_blank', 'noopener,noreferrer'); client.invalidateQueries({ queryKey: ['cadenza', 'enrollments'] }) } })
  const paymentHistory = useQuery({ queryKey: ['cadenza', 'payment-history', payment?.paymentObligationId], queryFn: () => paymentsApi.history(payment.paymentObligationId), enabled: Boolean(payment?.paymentObligationId) })
  const attachmentsQuery = useQuery({ queryKey: ['cadenza', 'attachments', attachmentPackage?.id], queryFn: () => lessonsApi.listAttachments(attachmentPackage.id), enabled: Boolean(attachmentPackage?.id) })
  const deleteAttachment = useMutation({ mutationFn: ({ packageId, id }) => lessonsApi.deleteAttachment(packageId, id), onSuccess: () => client.invalidateQueries({ queryKey: ['cadenza', 'attachments', attachmentPackage?.id] }) })
  const obligationQuery = useQuery({ queryKey: ['cadenza', 'payment', payment?.paymentObligationId], queryFn: () => paymentsApi.get(payment.paymentObligationId), enabled: Boolean(payment?.paymentObligationId) })
  if (packagesQuery.isLoading) return <LoadingState label="Loading lesson packages…" rows={3} />
  if (packagesQuery.error) return <Alert variant="destructive"><AlertDescription>{packagesQuery.error.message}</AlertDescription></Alert>
  const packages = unwrap(packagesQuery.data), students = unwrap(studentsQuery.data), enrollments = unwrap(enrollmentsQuery.data)
  const obligation = obligationQuery.data?.data ?? obligationQuery.data
  const due = obligation?.balanceDue ?? obligation?.totalAmount ?? payment?.amount
  const error = create.error || enroll.error || attach.error || pay.error || online.error
  return <div className="grid gap-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h1 className="text-2xl font-bold tracking-tight">Music Lessons</h1><p className="text-sm text-muted-foreground">Packages, materials, enrollments, and full-payment registration.</p></div><div className="flex gap-2">{canEnroll && <Button variant="outline" onClick={() => setEnrollOpen(true)}>Enroll</Button>}{canCreate && <Button onClick={() => setPackageOpen(true)}>Create package</Button>}</div></div>
    {error && <Alert variant="destructive"><AlertDescription>{error.message}</AlertDescription></Alert>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{packages.map((p) => <Card key={p.id}><CardHeader className="flex flex-row items-center justify-between space-y-0"><CardTitle className="text-base">{p.name}</CardTitle><Badge>{p.status}</Badge></CardHeader><CardContent className="space-y-3"><p className="text-sm">{p.numberOfSessions} sessions</p><p className="font-bold">{formatCurrency(p.price)}</p><p className="text-sm text-muted-foreground">{p._count?.attachments ?? 0} attachment(s)</p>{canManage && <Button size="sm" variant="outline" onClick={() => setAttachmentPackage(p)}>Attach PDF</Button>}</CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle className="text-base">Enrollments</CardTitle></CardHeader><CardContent className="space-y-2">{enrollments.slice(0, 10).map((e) => <div key={e.id} className="flex flex-wrap items-center justify-between gap-2 border-b py-2 last:border-0"><span className="text-sm">{e.lessonPackage?.name ?? e.lessonPackageId}</span><Badge>{e.status}</Badge><span className="text-xs text-muted-foreground">{e.progress?.completedSessions ?? 0}/{e.progress?.totalSessions ?? 0} sessions completed</span></div>)}</CardContent></Card>
    <Dialog open={packageOpen} onOpenChange={setPackageOpen}><DialogContent><DialogHeader><DialogTitle>Create lesson package</DialogTitle></DialogHeader><div className="grid gap-4"><div className="grid gap-2"><Label>Name</Label><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.currentTarget.value })} /></div><div className="grid gap-2"><Label>Description</Label><Textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.currentTarget.value })} /></div><div className="grid gap-2"><Label>Price</Label><Input type="number" min="0.01" step="0.01" value={form.price} onChange={(e) => setForm({ ...form, price: e.currentTarget.value })} /></div><div className="grid gap-2"><Label>Sessions</Label><Input type="number" min="1" value={form.numberOfSessions} onChange={(e) => setForm({ ...form, numberOfSessions: e.currentTarget.value })} /></div></div><DialogFooter><Button disabled={!form.name || !form.price} onClick={() => create.mutate({ ...form, price: String(form.price), numberOfSessions: Number(form.numberOfSessions) })}>{create.isPending ? 'Creating…' : 'Create'}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={enrollOpen} onOpenChange={setEnrollOpen}><DialogContent><DialogHeader><DialogTitle>Enroll student</DialogTitle><DialogDescription>Enrollment creates a full-payment obligation.</DialogDescription></DialogHeader><div className="grid gap-4"><SelectField label="Student" options={students.map((s) => ({ value: s.id, label: s.person?.name ?? s.person?.fullName ?? s.id }))} value={enrollForm.studentId} onChange={(v) => setEnrollForm({ ...enrollForm, studentId: v || '' })} placeholder="Choose a student" /><SelectField label="Package" options={packages.filter((p) => p.status === 'ACTIVE').map((p) => ({ value: p.id, label: p.name }))} value={enrollForm.lessonPackageId} onChange={(v) => setEnrollForm({ ...enrollForm, lessonPackageId: v || '' })} placeholder="Choose a package" /></div><DialogFooter><Button disabled={!enrollForm.studentId || !enrollForm.lessonPackageId} onClick={() => enroll.mutate(enrollForm)}>{enroll.isPending ? 'Creating…' : 'Create full-payment enrollment'}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(attachmentPackage)} onOpenChange={(open) => !open && setAttachmentPackage(null)}><DialogContent><DialogHeader><DialogTitle>Lesson materials</DialogTitle></DialogHeader><div className="grid gap-3">{(attachmentsQuery.data?.data ?? attachmentsQuery.data ?? []).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 border-b py-2"><span className="text-sm">{item.metadata?.fileName ?? item.type}</span><div className="flex gap-2"><Button size="sm" variant="outline" onClick={async () => { const response = await lessonsApi.getAttachmentUrl(attachmentPackage.id, item.id); const value = response?.data ?? response; if (value?.url) window.open(value.url, '_blank', 'noopener,noreferrer') }}>View</Button>{canManage && <Button size="sm" variant="destructive" onClick={() => deleteAttachment.mutate({ packageId: attachmentPackage.id, id: item.id })}>Delete</Button>}</div></div>)}<Input type="file" accept="application/pdf" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /><Button disabled={!file} onClick={() => attach.mutate({ packageId: attachmentPackage.id, selectedFile: file })}>{attach.isPending ? 'Uploading…' : 'Upload'}</Button></div></DialogContent></Dialog>
    <Dialog open={Boolean(payment)} onOpenChange={(open) => !open && setPayment(null)}><DialogContent><DialogHeader><DialogTitle>Lesson payment</DialogTitle><DialogDescription>Enrollment requires full payment.</DialogDescription></DialogHeader><div className="grid gap-4"><p className="font-bold">Balance: {formatCurrency(due)}</p><Separator />{(paymentHistory.data?.data ?? paymentHistory.data ?? []).map((entry) => <p key={entry.id} className="text-xs text-muted-foreground">{new Date(entry.createdAt).toLocaleString()} — {formatCurrency(entry.amount)} — {entry.status}</p>)}<Button disabled={!due} onClick={() => pay.mutate({ id: payment.paymentObligationId, amount: due })}>{pay.isPending ? 'Recording…' : 'Record full payment'}</Button><Button variant="outline" disabled={!due} onClick={() => online.mutate({ id: payment.paymentObligationId, amount: due })}>{online.isPending ? 'Opening…' : 'Pay online'}</Button></div></DialogContent></Dialog>
  </div>
}
