import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, AlertDescription } from '../../../components/ui/alert'
import { Badge } from '../../../components/ui/badge'
import { Button } from '../../../components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/card'
import DataTable from '../../../components/data-table'
import PageHeader from '../../../components/page-header'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../../components/ui/dialog'
import { Input } from '../../../components/ui/input'
import { Label } from '../../../components/ui/label'
import { Separator } from '../../../components/ui/separator'
import { Textarea } from '../../../components/ui/textarea'
import SelectField from '../../../components/select-field'
import LoadingState from '../../../components/loading-state'
import { formatCurrency } from '../../../utils/currency'
import { lessonsApi } from '../api/lessons.api'
import { customersApi } from '../../customers/api/customers.api'
import { paymentsApi } from '../../payments/api/payments.api'
import { useAuthorization } from '../../authorization/components/AuthorizationProvider'

const unwrap = (r) => r?.data ?? r ?? []
const readBase64 = (file) => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = reject; reader.readAsDataURL(file) })

export default function LessonsPage() {
  const { can } = useAuthorization()
  const client = useQueryClient()
  const canCreate = can('cadenza_lessons:create'), canEnroll = can('cadenza_enrollments:create'), canManage = can('cadenza_lessons:manage'), canEnrollmentManage = can('cadenza_enrollments:manage'), canPay = can('cadenza_payments:create')
  const packagesQuery = useQuery({ queryKey: ['cadenza', 'lesson-packages'], queryFn: lessonsApi.listPackages })
  const customersQuery = useQuery({ queryKey: ['cadenza', 'customers'], queryFn: customersApi.list, enabled: canEnrollmentManage })
  const enrollmentsQuery = useQuery({ queryKey: ['cadenza', 'enrollments'], queryFn: lessonsApi.listEnrollments })
  const [packageOpen, setPackageOpen] = useState(false), [enrollOpen, setEnrollOpen] = useState(false), [attachmentPackage, setAttachmentPackage] = useState(null), [payment, setPayment] = useState(null), [file, setFile] = useState(null)
  const [form, setForm] = useState({ name: '', description: '', price: '', numberOfSessions: 1 })
  const [enrollForm, setEnrollForm] = useState({ customerId: '', lessonPackageId: '' })
  const create = useMutation({ mutationFn: lessonsApi.createPackage, onSuccess: () => { setPackageOpen(false); client.invalidateQueries({ queryKey: ['cadenza', 'lesson-packages'] }) } })
  const enroll = useMutation({ mutationFn: lessonsApi.enroll, onSuccess: (r) => { setEnrollOpen(false); client.invalidateQueries({ queryKey: ['cadenza', 'enrollments'] }); client.invalidateQueries({ queryKey: ['cadenza', 'customers'] }); const v = r?.data ?? r; if (v?.paymentObligationId) setPayment(v) } })
  const attach = useMutation({ mutationFn: async ({ packageId, selectedFile }) => lessonsApi.addAttachment(packageId, { fileName: selectedFile.name, contentBase64: await readBase64(selectedFile), contentType: selectedFile.type || 'application/pdf', type: 'PDF' }), onSuccess: () => { setAttachmentPackage(null); setFile(null); client.invalidateQueries({ queryKey: ['cadenza', 'lesson-packages'] }) } })
  const pay = useMutation({ mutationFn: ({ id, amount }) => paymentsApi.pay(id, { amount: String(amount), currency: 'PHP', method: 'CASH' }), onSuccess: () => { client.invalidateQueries({ queryKey: ['cadenza', 'enrollments'] }); client.invalidateQueries({ queryKey: ['cadenza', 'payment', payment?.paymentObligationId] }); client.invalidateQueries({ queryKey: ['cadenza', 'payment-history', payment?.paymentObligationId] }) } })
  const online = useMutation({ mutationFn: ({ id, amount }) => paymentsApi.checkout(id, { amount: String(amount), description: 'Cadenza lesson enrollment' }), onSuccess: (response) => { const value = response?.data ?? response; if (value?.checkoutUrl) window.open(value.checkoutUrl, '_blank', 'noopener,noreferrer'); client.invalidateQueries({ queryKey: ['cadenza', 'enrollments'] }) } })
  const paymentHistory = useQuery({ queryKey: ['cadenza', 'payment-history', payment?.paymentObligationId], queryFn: () => paymentsApi.history(payment.paymentObligationId), enabled: Boolean(payment?.paymentObligationId) })
  const attachmentsQuery = useQuery({ queryKey: ['cadenza', 'attachments', attachmentPackage?.id], queryFn: () => lessonsApi.listAttachments(attachmentPackage.id), enabled: Boolean(attachmentPackage?.id) })
  const deleteAttachment = useMutation({ mutationFn: ({ packageId, id }) => lessonsApi.deleteAttachment(packageId, id), onSuccess: () => client.invalidateQueries({ queryKey: ['cadenza', 'attachments', attachmentPackage?.id] }) })
  const obligationQuery = useQuery({ queryKey: ['cadenza', 'payment', payment?.paymentObligationId], queryFn: () => paymentsApi.get(payment.paymentObligationId), enabled: Boolean(payment?.paymentObligationId) })
  if (packagesQuery.isLoading || (canEnrollmentManage && customersQuery.isLoading)) return <LoadingState label="Loading lesson packages…" rows={3} />
  if (packagesQuery.error || customersQuery.error) return <Alert variant="destructive"><AlertDescription>{(packagesQuery.error || customersQuery.error).message}</AlertDescription></Alert>
  const packages = unwrap(packagesQuery.data), customers = unwrap(customersQuery.data), enrollments = unwrap(enrollmentsQuery.data)
  const obligation = obligationQuery.data?.data ?? obligationQuery.data
  const due = obligation?.balanceDue ?? obligation?.totalAmount ?? payment?.amount
  const openPayment = (enrollment) => setPayment({ ...enrollment, paymentObligationId: enrollment.paymentObligationId })
  const error = create.error || enroll.error || attach.error || pay.error || online.error
  return <div className="grid gap-6">
    <PageHeader title="Music Lessons" description="Packages, materials, enrollments, and full-payment registration." actions={<>{canEnroll && <Button variant="outline" onClick={() => setEnrollOpen(true)}>Enroll</Button>}{canCreate && <Button onClick={() => setPackageOpen(true)}>Create package</Button>}</>} />
    {error && <Alert variant="destructive"><AlertDescription>{error.message}</AlertDescription></Alert>}
    <Card><CardContent className="pt-6"><DataTable columns={[{ key: "name", header: "Package", value: (p) => p.name }, { key: "sessions", header: "Sessions", value: (p) => p.numberOfSessions }, { key: "price", header: "Price", value: (p) => formatCurrency(p.price) }, { key: "status", header: "Status", render: (p) => <Badge variant="secondary">{p.status}</Badge> }, { key: "attachments", header: "Materials", value: (p) => p._count?.attachments ?? 0 }, { key: "actions", header: "Actions", searchable: false, render: (p) => canManage ? <Button size="sm" variant="outline" onClick={() => setAttachmentPackage(p)}>Attach PDF</Button> : null }]} rows={packages} searchPlaceholder="Search lesson packages…" /></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Enrollments</CardTitle></CardHeader><CardContent><DataTable columns={[{ key: "package", header: "Package", value: (e) => e.lessonPackage?.name ?? e.lessonPackageId }, { key: "status", header: "Status", render: (e) => <Badge variant="secondary">{e.status}</Badge> }, { key: "progress", header: "Progress", value: (e) => `${e.progress?.completedSessions ?? 0}/${e.progress?.totalSessions ?? 0} sessions` }, { key: "payment", header: "Payment", render: (e) => <Badge variant="secondary">{e.paymentObligationId ? (e.status === 'PENDING_PAYMENT' ? 'Payment due' : 'Payment linked') : '—'}</Badge> }, { key: "actions", header: "Actions", searchable: false, render: (e) => e.paymentObligationId && canPay && e.status === 'PENDING_PAYMENT' ? <Button size="sm" onClick={() => openPayment(e)}>Pay enrollment</Button> : null }]} rows={enrollments} searchPlaceholder="Search enrollments…" /></CardContent></Card>
    <Dialog open={packageOpen} onOpenChange={setPackageOpen}><DialogContent><DialogHeader><DialogTitle>Create lesson package</DialogTitle></DialogHeader><div className="grid gap-4"><div className="grid gap-2"><Label>Name</Label><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.currentTarget.value })} /></div><div className="grid gap-2"><Label>Description</Label><Textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.currentTarget.value })} /></div><div className="grid gap-2"><Label>Price</Label><Input type="number" min="0.01" step="0.01" value={form.price} onChange={(e) => setForm({ ...form, price: e.currentTarget.value })} /></div><div className="grid gap-2"><Label>Sessions</Label><Input type="number" min="1" value={form.numberOfSessions} onChange={(e) => setForm({ ...form, numberOfSessions: e.currentTarget.value })} /></div></div><DialogFooter><Button disabled={!form.name || !form.price} onClick={() => create.mutate({ ...form, price: String(form.price), numberOfSessions: Number(form.numberOfSessions) })}>{create.isPending ? 'Creating…' : 'Create'}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={enrollOpen} onOpenChange={setEnrollOpen}><DialogContent><DialogHeader><DialogTitle>{canEnrollmentManage ? 'Enroll customer' : 'Enroll in a lesson package'}</DialogTitle><DialogDescription>{canEnrollmentManage ? 'Enrollment creates a full-payment obligation.' : 'You will be registered as a Cadenza customer automatically, then enrolled with a full-payment obligation.'}</DialogDescription></DialogHeader><div className="grid gap-4">{canEnrollmentManage && <SelectField label="Customer" options={customers.map((s) => ({ value: s.id, label: s.person?.name ?? s.person?.fullName ?? s.id }))} value={enrollForm.customerId} onChange={(v) => setEnrollForm({ ...enrollForm, customerId: v || '' })} placeholder="Choose a customer" />}<SelectField label="Package" options={packages.filter((p) => p.status === 'ACTIVE').map((p) => ({ value: p.id, label: p.name }))} value={enrollForm.lessonPackageId} onChange={(v) => setEnrollForm({ ...enrollForm, lessonPackageId: v || '' })} placeholder="Choose a package" /></div><DialogFooter><Button disabled={!enrollForm.lessonPackageId || (canEnrollmentManage && !enrollForm.customerId)} onClick={() => enroll.mutate(canEnrollmentManage ? enrollForm : { lessonPackageId: enrollForm.lessonPackageId })}>{enroll.isPending ? 'Creating…' : 'Create full-payment enrollment'}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(attachmentPackage)} onOpenChange={(open) => !open && setAttachmentPackage(null)}><DialogContent><DialogHeader><DialogTitle>Lesson materials</DialogTitle></DialogHeader><div className="grid gap-3">{(attachmentsQuery.data?.data ?? attachmentsQuery.data ?? []).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 border-b py-2"><span className="text-sm">{item.metadata?.fileName ?? item.type}</span><div className="flex gap-2"><Button size="sm" variant="outline" onClick={async () => { const response = await lessonsApi.getAttachmentUrl(attachmentPackage.id, item.id); const value = response?.data ?? response; if (value?.url) window.open(value.url, '_blank', 'noopener,noreferrer') }}>View</Button>{canManage && <Button size="sm" variant="destructive" onClick={() => deleteAttachment.mutate({ packageId: attachmentPackage.id, id: item.id })}>Delete</Button>}</div></div>)}<Input type="file" accept="application/pdf" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /><Button disabled={!file} onClick={() => attach.mutate({ packageId: attachmentPackage.id, selectedFile: file })}>{attach.isPending ? 'Uploading…' : 'Upload'}</Button></div></DialogContent></Dialog>
    <Dialog open={Boolean(payment)} onOpenChange={(open) => !open && setPayment(null)}><DialogContent><DialogHeader><DialogTitle>Lesson payment</DialogTitle><DialogDescription>Enrollment requires full payment.</DialogDescription></DialogHeader><div className="grid gap-4"><p className="font-bold">Balance: {formatCurrency(due)}</p><p className="text-sm text-muted-foreground">{payment?.lessonPackage?.name ? `Enrollment: ${payment.lessonPackage.name}` : 'Lesson enrollment'}</p><Separator />{(paymentHistory.data?.data ?? paymentHistory.data ?? []).map((entry) => <p key={entry.id} className="text-xs text-muted-foreground">{new Date(entry.createdAt).toLocaleString()} — {formatCurrency(entry.amount)} — {entry.status}</p>)}<Button disabled={!due || !canPay || pay.isPending} onClick={() => pay.mutate({ id: payment.paymentObligationId, amount: due })}>{pay.isPending ? 'Recording…' : 'Record full payment'}</Button><Button variant="outline" disabled={!due || !canPay || online.isPending} onClick={() => online.mutate({ id: payment.paymentObligationId, amount: due })}>{online.isPending ? 'Opening…' : 'Pay online'}</Button></div></DialogContent></Dialog>
  </div>
}
