import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, AlertDescription } from '../../../components/ui/alert'
import { Badge } from '../../../components/ui/badge'
import { Button } from '../../../components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/card'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../../components/ui/dialog'
import { Input } from '../../../components/ui/input'
import { Label } from '../../../components/ui/label'
import SelectField from '../../../components/common/SelectField'
import LoadingState from '../../../components/common/LoadingState'
import { resourcesApi } from '../api/resources.api'
import { useAuthorization } from '../../authorization/components/AuthorizationProvider'

const unwrap = (r) => r?.data ?? r ?? []
export default function ResourcesPage() {
  const { can } = useAuthorization(), client = useQueryClient()
  const canCreate = can('cadenza_instruments:create') || can('cadenza_rooms:create'), canUpdate = can('cadenza_instruments:update') || can('cadenza_rooms:update')
  const instruments = useQuery({ queryKey: ['cadenza', 'instruments'], queryFn: resourcesApi.listInstruments }), rooms = useQuery({ queryKey: ['cadenza', 'rooms'], queryFn: resourcesApi.listRooms })
  const [open, setOpen] = useState(false), [editing, setEditing] = useState(null)
  const [form, setForm] = useState({ kind: 'INSTRUMENT', key: '', name: '', instrumentType: '', roomType: '', capacity: 1, rentalRate: '' })
  const createResource = useMutation({ mutationFn: resourcesApi.createResource }), createInstrument = useMutation({ mutationFn: resourcesApi.createInstrument, onSuccess: () => client.invalidateQueries({ queryKey: ['cadenza', 'instruments'] }) }), createRoom = useMutation({ mutationFn: resourcesApi.createRoom, onSuccess: () => client.invalidateQueries({ queryKey: ['cadenza', 'rooms'] }) })
  const updateInstrument = useMutation({ mutationFn: ({ id, payload }) => resourcesApi.updateInstrument(id, payload), onSuccess: () => { setEditing(null); client.invalidateQueries({ queryKey: ['cadenza', 'instruments'] }) } }), updateRoom = useMutation({ mutationFn: ({ id, payload }) => resourcesApi.updateRoom(id, payload), onSuccess: () => { setEditing(null); client.invalidateQueries({ queryKey: ['cadenza', 'rooms'] }) } })
  if (instruments.isLoading || rooms.isLoading) return <LoadingState label="Loading resources…" rows={3} />
  if (instruments.error || rooms.error) return <Alert variant="destructive"><AlertDescription>{(instruments.error || rooms.error).message}</AlertDescription></Alert>
  const entries = [...unwrap(instruments.data).map((x) => ({ ...x, kind: 'Instrument', label: x.instrumentType })), ...unwrap(rooms.data).map((x) => ({ ...x, kind: 'Room', label: x.roomType }))]
  const submit = async () => { const r = await createResource.mutateAsync({ key: form.key, name: form.name, type: form.kind === 'ROOM' ? 'CADENZA_ROOM' : 'CADENZA_INSTRUMENT' }); const resourceId = r?.data?.id ?? r?.id; if (!resourceId) throw new Error('Resource creation did not return an id.'); if (form.kind === 'ROOM') await createRoom.mutateAsync({ resourceId, roomType: form.roomType, capacity: Number(form.capacity), rentalRate: String(form.rentalRate) }); else await createInstrument.mutateAsync({ resourceId, instrumentType: form.instrumentType, rentalRate: String(form.rentalRate) }); setOpen(false); setForm({ kind: form.kind, key: '', name: '', instrumentType: '', roomType: '', capacity: 1, rentalRate: '' }); await client.invalidateQueries({ queryKey: ['cadenza', 'instruments'] }); await client.invalidateQueries({ queryKey: ['cadenza', 'rooms'] }) }
  const error = createResource.error || createInstrument.error || createRoom.error
  return <div className="grid gap-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h1 className="text-2xl font-bold tracking-tight">Resources</h1><p className="text-sm text-muted-foreground">Cadenza instruments and band rooms.</p></div>{canCreate && <Button onClick={() => setOpen(true)}>Add resource</Button>}</div>{error && <Alert variant="destructive"><AlertDescription>{error.message}</AlertDescription></Alert>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{entries.map((x) => <Card key={x.id}><CardHeader className="flex flex-row items-center justify-between space-y-0"><CardTitle className="text-base">{x.label}</CardTitle><Badge>{x.status}</Badge></CardHeader><CardContent className="space-y-3"><p className="text-sm">{x.kind}</p><p className="font-medium">₱{Number(x.rentalRate).toLocaleString()} / hour</p>{canUpdate && <Button size="sm" variant="outline" onClick={() => setEditing(x)}>Edit</Button>}</CardContent></Card>)}</div>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Add resource</DialogTitle></DialogHeader><div className="grid gap-4"><SelectField label="Type" options={[{ value: 'INSTRUMENT', label: 'Instrument' }, { value: 'ROOM', label: 'Band room' }]} value={form.kind} onChange={(v) => setForm({ ...form, kind: v || 'INSTRUMENT' })} /><div className="grid gap-2"><Label>Resource key</Label><Input value={form.key} onChange={(e) => setForm({ ...form, key: e.currentTarget.value })} /></div><div className="grid gap-2"><Label>Name</Label><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.currentTarget.value })} /></div>{form.kind === 'ROOM' ? <><div className="grid gap-2"><Label>Room type</Label><Input value={form.roomType} onChange={(e) => setForm({ ...form, roomType: e.currentTarget.value })} /></div><div className="grid gap-2"><Label>Capacity</Label><Input type="number" min="1" value={form.capacity} onChange={(e) => setForm({ ...form, capacity: e.currentTarget.value })} /></div></> : <div className="grid gap-2"><Label>Instrument type</Label><Input value={form.instrumentType} onChange={(e) => setForm({ ...form, instrumentType: e.currentTarget.value })} /></div>}<div className="grid gap-2"><Label>Hourly rate</Label><Input type="number" min="0.01" step="0.01" value={form.rentalRate} onChange={(e) => setForm({ ...form, rentalRate: e.currentTarget.value })} /></div></div><DialogFooter><Button disabled={!form.key || !form.name || !form.rentalRate} onClick={submit}>{createResource.isPending || createInstrument.isPending || createRoom.isPending ? 'Creating…' : 'Create'}</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(editing)} onOpenChange={(value) => !value && setEditing(null)}><DialogContent><DialogHeader><DialogTitle>Update resource</DialogTitle></DialogHeader><div className="grid gap-4"><SelectField label="Status" options={['AVAILABLE', 'UNAVAILABLE', 'MAINTENANCE', 'RETIRED'].map((x) => ({ value: x, label: x }))} value={editing?.status} onChange={(v) => setEditing({ ...editing, status: v })} /><div className="grid gap-2"><Label>Hourly rate</Label><Input type="number" min="0.01" step="0.01" value={editing?.rentalRate ?? ''} onChange={(e) => setEditing({ ...editing, rentalRate: e.currentTarget.value })} /></div></div><DialogFooter><Button onClick={() => editing.kind === 'Instrument' ? updateInstrument.mutate({ id: editing.id, payload: { status: editing.status, rentalRate: String(editing.rentalRate) } }) : updateRoom.mutate({ id: editing.id, payload: { status: editing.status, rentalRate: String(editing.rentalRate) } })}>{updateInstrument.isPending || updateRoom.isPending ? 'Saving…' : 'Save'}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
