import {useMemo,useState} from 'react'
import {Outlet} from 'react-router-dom'
import {AppShell,Drawer,useMatches} from '@mantine/core'
import {useAuth} from '../features/auth/components/AuthProvider'
import {useAuthorization} from '../features/authorization/components/AuthorizationProvider'
import {navigation,normalizeNavigation} from '../config/navigation'
import {layout} from '../config/layout'
import Sidebar from './components/Sidebar'
import TopBar from './components/TopBar'
import PageContainer from './components/PageContainer'
export default function CadenzaLayout(){const{user,logout}=useAuth();const{context,isLoading}=useAuthorization();const desktop=useMatches({base:false,[layout.breakpoint]:true});const[mobileOpen,setMobileOpen]=useState(false);const[collapsed,setCollapsed]=useState(false);const nav=useMemo(()=>normalizeNavigation(navigation,context?.permissions),[context?.permissions]);const sidebar=(c=false)=><Sidebar navigation={nav} navigationLoading={isLoading} user={user} role={context?.role?.name} collapsed={c} onNavigate={()=>setMobileOpen(false)} onLogout={()=>void logout()} onToggleCollapse={()=>setCollapsed(v=>!v)}/>;return <AppShell className="cadenza-app" header={{height:layout.headerHeight}} navbar={{width:collapsed?layout.sidebarCollapsedWidth:layout.sidebarWidth,breakpoint:layout.breakpoint,collapsed:{mobile:true,desktop:false}}} padding={0}><AppShell.Header className="cadenza-topbar"><TopBar onMenu={()=>setMobileOpen(true)} navigation={nav} onNavigate={()=>setMobileOpen(false)}/></AppShell.Header><AppShell.Navbar className="cadenza-sidebar">{sidebar(collapsed)}</AppShell.Navbar>{!desktop&&<Drawer opened={mobileOpen} onClose={()=>setMobileOpen(false)} size={320} withCloseButton={false} padding={0}>{sidebar(false)}</Drawer>}<AppShell.Main><PageContainer><main id="cadenza-main"><Outlet/></main></PageContainer></AppShell.Main></AppShell>}
