import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, Badge, Button, Card, Group, Modal, Select, SimpleGrid, Stack, Text, TextInput, Textarea, Title } from '@mantine/core'
import LoadingState from '../../../components/common/LoadingState'
import { schedulingApi } from '../api/scheduling.api'
import { lessonsApi } from '../../lessons/api/lessons.api'
import { instructorsApi } from '../../instructors/api/instructors.api'
import { resourcesApi } from '../../resources/api/resources.api'
import { useAuthorization } from '../../authorization/components/AuthorizationProvider'
const unwrap=r=>r?.data??r??[]
export default function LessonSchedulePage(){
 const {can}=useAuthorization(),client=useQueryClient()
 const canCreate=can('cadenza_lessons:schedule'),canAttendance=can('cadenza_lessons:attendance'),canRequest=can('cadenza_lessons:request_reschedule'),canManage=can('cadenza_lessons:manage'),canInstructorRead=can('cadenza_instructors:read'),canRoomRead=can('cadenza_rooms:read')
 const sessions=useQuery({queryKey:['cadenza','sessions'],queryFn:schedulingApi.listSessions}),enrollments=useQuery({queryKey:['cadenza','enrollments'],queryFn:lessonsApi.listEnrollments}),instructors=useQuery({queryKey:['cadenza','instructors'],queryFn:instructorsApi.list,enabled:canInstructorRead}),rooms=useQuery({queryKey:['cadenza','rooms'],queryFn:resourcesApi.listRooms,enabled:canRoomRead}),reschedules=useQuery({queryKey:['cadenza','reschedules'],queryFn:schedulingApi.listReschedules})
 const [form,setForm]=useState({enrollmentId:null,instructorId:null,roomId:null,scheduledStart:'',scheduledEnd:''}),[selected,setSelected]=useState(null),[requestOpen,setRequestOpen]=useState(null),[attendance,setAttendance]=useState('PRESENT'),[notes,setNotes]=useState('')
 const create=useMutation({mutationFn:schedulingApi.createSession,onSuccess:()=>{setForm({enrollmentId:null,instructorId:null,roomId:null,scheduledStart:'',scheduledEnd:''});client.invalidateQueries({queryKey:['cadenza','sessions']})}})
 const mark=useMutation({mutationFn:({id,payload})=>schedulingApi.markAttendance(id,payload),onSuccess:()=>{setSelected(null);client.invalidateQueries({queryKey:['cadenza','sessions']})}})
 const transition=useMutation({mutationFn:({type,id})=>schedulingApi[type](id),onSuccess:()=>client.invalidateQueries({queryKey:['cadenza','sessions']})})
 const request=useMutation({mutationFn:schedulingApi.requestReschedule,onSuccess:()=>setRequestOpen(null)})
 const review=useMutation({mutationFn:({id,approve})=>schedulingApi.reviewReschedule(id,approve),onSuccess:()=>client.invalidateQueries({queryKey:['cadenza','reschedules']})})
 if(sessions.isLoading)return <LoadingState label="Loading schedule…" rows={4}/>
 if(sessions.error)return <Alert color="red">{sessions.error.message}</Alert>
 const rows=unwrap(sessions.data),confirmed=unwrap(enrollments.data).filter(e=>e.status==='CONFIRMED'),instructorRows=unwrap(instructors.data),roomRows=unwrap(rooms.data),pending=unwrap(reschedules.data).filter(r=>r.status==='PENDING')
 const openSchedule=()=>setForm({...form,enrollmentId:confirmed[0]?.id??null})
 return <Stack gap="lg"><Group justify="space-between"><div><Title order={2}>Lesson Schedule</Title><Text c="dimmed">Session scheduling, attendance, assignments, and rescheduling.</Text></div>{canCreate&&<Button onClick={openSchedule}>Schedule session</Button>}</Group>
 {(create.error||mark.error||transition.error||request.error||review.error)&&<Alert color="red">{(create.error||mark.error||transition.error||request.error||review.error).message}</Alert>}
 {canManage&&<Card withBorder><Group justify="space-between"><Title order={4}>Pending reschedules</Title><Badge>{pending.length}</Badge></Group>{pending.map(r=><Group key={r.id} justify="space-between" mt="sm"><Text size="sm">{new Date(r.requestedStart).toLocaleString()}</Text><Group><Button size="xs" onClick={()=>review.mutate({id:r.id,approve:true})}>Approve</Button><Button size="xs" color="red" onClick={()=>review.mutate({id:r.id,approve:false})}>Reject</Button></Group></Group>)}</Card>}
 <SimpleGrid cols={{base:1,md:2,lg:3}}>{rows.map(s=><Card key={s.id} withBorder><Stack><Group justify="space-between"><Text fw={700}>{new Date(s.scheduledStart).toLocaleString()}</Text><Badge>{s.status}</Badge></Group><Text size="sm">Instructor: {s.instructor?.person?.name??s.instructorId??'Unassigned'}</Text><Text size="sm">Room: {s.roomId??'Unassigned'}</Text>{s.attendance&&<Text size="sm">Attendance: {s.attendance.status}</Text>}<Group>{canAttendance&&s.status==='SCHEDULED'&&<Button size="xs" onClick={()=>setSelected(s)}>Attendance</Button>}{canRequest&&s.status==='SCHEDULED'&&<Button size="xs" variant="light" onClick={()=>setRequestOpen({id:s.id,requestedStart:'',requestedEnd:'',reason:''})}>Reschedule</Button>}{canManage&&s.status==='SCHEDULED'&&<><Button size="xs" onClick={()=>transition.mutate({type:'completeSession',id:s.id})}>Complete</Button><Button size="xs" color="red" onClick={()=>transition.mutate({type:'cancelSession',id:s.id})}>Cancel</Button></>}</Group></Stack></Card>)}</SimpleGrid>
 <Modal opened={Boolean(form.enrollmentId)} onClose={()=>setForm({...form,enrollmentId:null})} title="Schedule session"><Stack><Select label="Enrollment" data={confirmed.map(e=>({value:e.id,label:e.lessonPackage?.name??e.id}))} value={form.enrollmentId} onChange={v=>setForm({...form,enrollmentId:v})}/><Select label="Instructor" clearable data={instructorRows.map(i=>({value:i.id,label:i.person?.name??i.id}))} value={form.instructorId} onChange={v=>setForm({...form,instructorId:v})}/><Select label="Room" clearable data={roomRows.map(r=>({value:r.id,label:r.roomType??r.id}))} value={form.roomId} onChange={v=>setForm({...form,roomId:v})}/><TextInput label="Start" type="datetime-local" value={form.scheduledStart} onChange={e=>setForm({...form,scheduledStart:e.currentTarget.value})}/><TextInput label="End" type="datetime-local" value={form.scheduledEnd} onChange={e=>setForm({...form,scheduledEnd:e.currentTarget.value})}/><Button loading={create.isPending} disabled={!form.enrollmentId||!form.scheduledStart||!form.scheduledEnd} onClick={()=>create.mutate({...form,scheduledStart:new Date(form.scheduledStart).toISOString(),scheduledEnd:new Date(form.scheduledEnd).toISOString()})}>Schedule</Button></Stack></Modal>
 <Modal opened={Boolean(selected)} onClose={()=>setSelected(null)} title="Attendance"><Stack><Select label="Status" data={['PRESENT','ABSENT','LATE','EXCUSED']} value={attendance} onChange={v=>setAttendance(v||'PRESENT')}/><Textarea label="Notes" value={notes} onChange={e=>setNotes(e.currentTarget.value)}/><Button loading={mark.isPending} onClick={()=>mark.mutate({id:selected.id,payload:{status:attendance,notes:notes||undefined}})}>Save</Button></Stack></Modal>
 <Modal opened={Boolean(requestOpen)} onClose={()=>setRequestOpen(null)} title="Request reschedule"><Stack><TextInput label="Start" type="datetime-local" value={requestOpen?.requestedStart??''} onChange={e=>setRequestOpen({...requestOpen,requestedStart:e.currentTarget.value})}/><TextInput label="End" type="datetime-local" value={requestOpen?.requestedEnd??''} onChange={e=>setRequestOpen({...requestOpen,requestedEnd:e.currentTarget.value})}/><Textarea label="Reason" value={requestOpen?.reason??''} onChange={e=>setRequestOpen({...requestOpen,reason:e.currentTarget.value})}/><Button loading={request.isPending} onClick={()=>request.mutate({sessionId:requestOpen.id,requestedStart:new Date(requestOpen.requestedStart).toISOString(),requestedEnd:new Date(requestOpen.requestedEnd).toISOString(),reason:requestOpen.reason||undefined})}>Submit</Button></Stack></Modal>
 </Stack>
}
