import {BadRequestError,ConflictError,NotFoundError} from '../../../common/errors/appError.js'
import {requireAppId} from '../../../platform/applications/application-scope.js'
import {createPaymentObligation} from '../../../platform/payments/payment.service.js'
import * as repository from './lesson.repository.js'
const listPackages=({appId})=>repository.listPackages(requireAppId(appId))
const createPackage=async({appId,name,description,price,numberOfSessions})=>{const owner=requireAppId(appId);const amount=Number(price);if(!name?.trim())throw new BadRequestError('name is required.');if(!Number.isFinite(amount)||amount<=0)throw new BadRequestError('price must be greater than zero.');if(!Number.isInteger(Number(numberOfSessions))||Number(numberOfSessions)<=0)throw new BadRequestError('numberOfSessions must be greater than zero.');try{return await repository.createPackage({appId:owner,name:name.trim(),description:description?.trim()||null,price,numberOfSessions:Number(numberOfSessions)})}catch(e){if(e?.code==='P2002')throw new ConflictError('Lesson package name is already used in this application.');throw e}}
const listEnrollments=({appId})=>repository.listEnrollments(requireAppId(appId))
const enroll=async({appId,studentId,lessonPackageId,currency='PHP'})=>{const owner=requireAppId(appId);if(!(await repository.findStudent(studentId,owner)))throw new NotFoundError('Student not found.');const pkg=await repository.findPackage(lessonPackageId,owner);if(!pkg)throw new NotFoundError('Lesson package not found.');try{return await repository.withTransaction(async(tx)=>{const enrollment=await repository.createEnrollment({appId:owner,studentId,lessonPackageId,status:'PENDING_PAYMENT'},tx);const obligation=await createPaymentObligation({appId:owner,referenceType:'CADENZA_ENROLLMENT',referenceId:enrollment.id,totalAmount:pkg.price,currency,db:tx,metadata:{requirement:'FULL_PAYMENT'}});return repository.attachPaymentObligation(enrollment.id,owner,obligation.id,tx)})}catch(e){if(e?.code==='P2002')throw new ConflictError('Student is already enrolled in this lesson package.');throw e}}
const listEnrollmentsForApp=({appId})=>repository.listEnrollments(requireAppId(appId))
const listSessions=({appId})=>repository.listSessions(requireAppId(appId))
const createSession=async({appId,enrollmentId,instructorId,roomId,scheduledStart,scheduledEnd})=>{const owner=requireAppId(appId);const start=new Date(scheduledStart),end=new Date(scheduledEnd);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||start>=end)throw new BadRequestError('scheduledEnd must be after scheduledStart.');return repository.withTransaction(async(tx)=>{if(!await repository.findEnrollment(enrollmentId,owner,tx))throw new NotFoundError('Confirmed enrollment not found.');if(instructorId&&!await repository.findInstructor(instructorId,owner,tx))throw new NotFoundError('Instructor not found.');if(roomId&&!await repository.findRoom(roomId,owner,tx))throw new NotFoundError('Room not found.');if(await repository.findOverlappingSession({appId:owner,instructorId,roomId,startsAt:start,endsAt:end},tx))throw new ConflictError('Instructor or room is already scheduled for an overlapping lesson session.');return repository.createSession({appId:owner,enrollmentId,instructorId:instructorId||null,roomId:roomId||null,scheduledStart:start,scheduledEnd:end,status:'SCHEDULED'},tx)})}
const markAttendance=async({appId,sessionId,status,markedByUserId,notes})=>{const owner=requireAppId(appId);return repository.withTransaction(async(tx)=>{if(!await repository.findSession(sessionId,owner,tx))throw new NotFoundError('Lesson session not found.');return repository.upsertAttendance(sessionId,{status,markedByUserId,notes:notes?.trim()||null},tx)})}
const requestReschedule=async({appId,sessionId,requestedByUserId,requestedStart,requestedEnd,reason})=>{const owner=requireAppId(appId);const start=new Date(requestedStart),end=new Date(requestedEnd);if(!(start<end))throw new BadRequestError('requestedEnd must be after requestedStart.');return repository.withTransaction(async(tx)=>{const session=await repository.findSession(sessionId,owner,tx);if(!session)throw new NotFoundError('Lesson session not found.');return repository.createReschedule({appId:owner,sessionId,requestedByUserId,requestedStart:start,requestedEnd:end,reason:reason?.trim()||null,status:'PENDING'},tx)})}
const reviewReschedule=async({appId,id,reviewedByUserId,approve})=>{const owner=requireAppId(appId);return repository.withTransaction(async(tx)=>{const request=await repository.findReschedule(id,owner,tx);if(!request)throw new NotFoundError('Reschedule request not found.');if(request.status!=='PENDING')throw new ConflictError('Only pending reschedule requests can be reviewed.');const session=await repository.findSession(request.sessionId,owner,tx);if(!session)throw new NotFoundError('Lesson session not found.');if(!approve){await repository.updateReschedule(id,owner,{status:'REJECTED',reviewedByUserId,reviewedAt:new Date()},tx);return repository.findReschedule(id,owner,tx)}if(await repository.findOverlappingSession({appId:owner,instructorId:session.instructorId,roomId:session.roomId,startsAt:request.requestedStart,endsAt:request.requestedEnd,excludeId:session.id},tx))throw new ConflictError('Instructor or room is already scheduled for an overlapping lesson session.');await repository.updateSession(session.id,owner,{scheduledStart:request.requestedStart,scheduledEnd:request.requestedEnd},tx);await repository.updateReschedule(id,owner,{status:'APPROVED',reviewedByUserId,reviewedAt:new Date()},tx);return repository.findReschedule(id,owner,tx)})}
export {listPackages,createPackage,listEnrollments:listEnrollmentsForApp,enroll,listSessions,createSession,markAttendance,requestReschedule,reviewReschedule}
