import { describe, expect, it, vi } from 'vitest'
import { createJobService, MAX_ATTEMPTS, MAX_BACKOFF_DELAY } from '../../../src/platform/jobs/job.service.js'
import { executeWithJobContext } from '../../../src/platform/jobs/job.worker.js'
import { getContext, runWithContext } from '../../../src/platform/context/context.service.js'
import { createBullMqInfrastructure } from '../../../src/infrastructure/queue/bullmq.js'

describe('platform jobs capability', () => {
  it('enqueues a job with stable defaults', async () => { const enqueueBullMqJob = vi.fn().mockResolvedValue({ id: 'job-1' }); const { enqueueJob } = createJobService({ enqueue: enqueueBullMqJob }); await enqueueJob({ queue: 'notifications', name: 'notification.delivery', data: { deliveryId: 'delivery-1' }, jobId: 'notification-delivery:delivery-1' }); expect(enqueueBullMqJob).toHaveBeenCalledWith('notifications', 'notification.delivery', { deliveryId: 'delivery-1' }, expect.objectContaining({ jobId: 'notification-delivery-delivery-1', attempts: 5, delay: 0, backoff: { type: 'exponential', delay: 1000 } })) })
  it('propagates the active platform context into job data', async () => { const enqueueBullMqJob = vi.fn().mockResolvedValue({ id: 'job-1' }); const { enqueueJob } = createJobService({ enqueue: enqueueBullMqJob }); await runWithContext({ requestId: 'req-1', correlationId: 'corr-1', actorId: 42, actorType: 'user', organizationId: 7 }, async () => { await enqueueJob({ queue: 'notifications', name: 'notification.delivery', data: { deliveryId: 'delivery-1' } }) }); expect(enqueueBullMqJob.mock.calls[0][2]).toEqual({ deliveryId: 'delivery-1', _platformContext: { requestId: 'req-1', correlationId: 'corr-1', actorId: 42, actorType: 'user', organizationId: 7 } }) })
  it('rejects unknown queues', async () => { const { enqueueJob } = createJobService({ enqueue: vi.fn() }); await expect(enqueueJob({ queue: 'missing', name: 'test', data: {} })).rejects.toThrow('Unknown job queue: missing') })
  it('rejects unsafe retry policies', async () => { const { enqueueJob } = createJobService({ enqueue: vi.fn() }); await expect(enqueueJob({ queue: 'notifications', name: 'test', data: {}, attempts: MAX_ATTEMPTS + 1 })).rejects.toThrow(`attempts must be an integer between 1 and ${MAX_ATTEMPTS}`); await expect(enqueueJob({ queue: 'notifications', name: 'test', data: {}, backoffDelay: MAX_BACKOFF_DELAY + 1 })).rejects.toThrow(`backoffDelay must be an integer between 0 and ${MAX_BACKOFF_DELAY}`); await expect(enqueueJob({ queue: 'notifications', name: 'test', data: {}, delay: -1 })).rejects.toThrow(`delay must be an integer between 0 and ${MAX_BACKOFF_DELAY}`) })
  it('restores the platform context while processing a job', async () => { const processor = vi.fn(async () => getContext()); const result = await executeWithJobContext({ data: { _platformContext: { requestId: 'req-1', correlationId: 'corr-1', actorId: 42, actorType: 'user', organizationId: 7 } } }, processor); expect(result).toMatchObject({ requestId: 'req-1', correlationId: 'corr-1', actorId: 42, actorType: 'user', organizationId: 7 }); expect(processor).toHaveBeenCalledOnce() })
  it('does not create context when a job has no platform context', async () => { const processor = vi.fn(async () => getContext()); await expect(executeWithJobContext({ data: {} }, processor)).resolves.toBeNull() })
  it('creates a queue with production retry and retention defaults', async () => { const queues = []; const workers = []; const events = []; const redis = { isOpen: true }; class MockQueue { constructor(name, options) { this.name = name; this.options = options; this.add = vi.fn(); this.getFailed = vi.fn(); this.getJob = vi.fn(); this.close = vi.fn().mockResolvedValue(undefined); queues.push(this) } } class MockWorker { constructor(name, processor, options) { this.name = name; this.processor = processor; this.options = options; this.handlers = new Map(); this.close = vi.fn().mockResolvedValue(undefined); this.on = vi.fn((event, handler) => { this.handlers.set(event, handler); return this }); workers.push(this) } } class MockQueueEvents { constructor(name, options) { this.name = name; this.options = options; this.close = vi.fn().mockResolvedValue(undefined); events.push(this) } } const infrastructure = createBullMqInfrastructure({ Queue: MockQueue, Worker: MockWorker, QueueEvents: MockQueueEvents, connectRedis: vi.fn(async () => redis), getRedisClient: vi.fn(() => redis), logger: { info: vi.fn(), error: vi.fn() } }); const instance = await infrastructure.getQueue('test-events'); expect(instance.options.defaultJobOptions).toEqual({ attempts: 5, backoff: { type: 'exponential', delay: 1000 }, removeOnComplete: { age: 86400, count: 1000 }, removeOnFail: false }) })
  it('enqueues named jobs with caller options', async () => { const queue = { add: vi.fn().mockResolvedValue({ id: 'job-1' }), close: vi.fn() }; const infrastructure = createBullMqInfrastructure({ Queue: class { constructor() { this.options = { defaultJobOptions: {} }; this.add = queue.add; this.close = queue.close } }, Worker: class {}, QueueEvents: class {}, connectRedis: vi.fn(async () => ({ isOpen: true })), getRedisClient: vi.fn(() => ({ isOpen: true })), logger: { info: vi.fn(), error: vi.fn() } }); const instance = await infrastructure.getQueue('test-events'); await expect(infrastructure.enqueueJob('test-events', 'platform-event', { event: 'created' }, { jobId: 'event-1', attempts: 3 })).resolves.toEqual({ id: 'job-1' }); expect(instance.add).toHaveBeenCalledWith('platform-event', { event: 'created' }, { jobId: 'event-1', attempts: 3 }) })
  it('registers workers with bounded concurrency and closes them gracefully', async () => { const workers = []; const infrastructure = createBullMqInfrastructure({ Queue: class {}, Worker: class { constructor(name, processor, options) { this.options = options; this.handlers = new Map(); this.close = vi.fn().mockResolvedValue(undefined); this.on = vi.fn((event, handler) => { this.handlers.set(event, handler); return this }) ; workers.push(this) } }, QueueEvents: class {}, connectRedis: vi.fn(async () => ({ isOpen: true })), getRedisClient: vi.fn(() => ({ isOpen: true })), logger: { info: vi.fn(), error: vi.fn() } }); await infrastructure.registerWorker('test-events', vi.fn(), { concurrency: 4 }); expect(workers[0].options.concurrency).toBe(4); expect(workers[0].handlers.has('failed')).toBe(true); await infrastructure.closeQueues(); expect(workers[0].close).toHaveBeenCalledOnce() })
})
