import { describe, expect, it, vi, beforeEach } from 'vitest'
const mocks = vi.hoisted(() => ({ repository: { createPolicy: vi.fn(), findPolicies: vi.fn(), findPolicyByKey: vi.fn(), createInstance: vi.fn(), findInstanceById: vi.fn(), updateInstance: vi.fn(), findDueInstances: vi.fn(), markBreached: vi.fn(), findEscalationCandidates: vi.fn(), markEscalated: vi.fn() }, recordAudit: vi.fn() }))
vi.mock('../../../src/platform/sla/sla.repository.js', () => mocks.repository)
vi.mock('../../../src/platform/audit/audit.service.js', () => ({ recordAudit: mocks.recordAudit }))
const { createSlaPolicy, findApplicablePolicy, startSla, completeSla, markDueSlas, markEscalations } = await import('../../../src/platform/sla/sla.service.js')

describe('SLA capability', () => {
  beforeEach(() => { for (const mock of Object.values(mocks.repository)) mock.mockReset(); mocks.recordAudit.mockReset() })
  it('rejects warning or escalation at or after the SLA deadline', async () => { await expect(createSlaPolicy({ key: 'sla-warning', name: 'SLA', entityType: 'CASE', durationSeconds: 300, warningSeconds: 300, conditions: { field: 'tier', operator: 'equals', value: 'gold' } })).rejects.toThrow('before the SLA deadline'); for (const escalationSeconds of [300, 301]) await expect(createSlaPolicy({ key: 'sla-escalation', name: 'SLA', entityType: 'CASE', durationSeconds: 300, escalationSeconds, conditions: { field: 'tier', operator: 'equals', value: 'gold' } })).rejects.toThrow('before the SLA deadline'); expect(mocks.repository.createPolicy).not.toHaveBeenCalled() })
  it('accepts valid warning and escalation before the deadline', async () => { mocks.repository.createPolicy.mockResolvedValue({ id: 'p1', key: 'sla' }); const result = await createSlaPolicy({ key: 'sla', name: 'SLA', entityType: 'CASE', durationSeconds: 300, warningSeconds: 120, escalationSeconds: 299, conditions: { field: 'tier', operator: 'equals', value: 'gold' } }); expect(result.id).toBe('p1'); expect(mocks.repository.createPolicy).toHaveBeenCalledOnce() })
  it('selects the first matching active policy in priority order', async () => { mocks.repository.findPolicies.mockResolvedValue([{ id: 'p-high', priority: 10, conditions: { field: 'tier', operator: 'equals', value: 'gold' } }, { id: 'p-low', priority: 20, conditions: { field: 'tier', operator: 'equals', value: 'gold' } }]); expect((await findApplicablePolicy({ entityType: 'CASE', context: { tier: 'gold' } })).id).toBe('p-high'); expect(mocks.repository.findPolicies).toHaveBeenCalledWith({ entityType: 'CASE', workflowStepKey: null }) })
  it('transitions an eligible SLA to ESCALATED without making it terminal', async () => { const startedAt = new Date('2026-08-17T07:00:00.000Z'); mocks.repository.findEscalationCandidates.mockResolvedValue([{ id: 's1', startedAt, policy: { escalationSeconds: 60 } }]); mocks.repository.markEscalated.mockResolvedValue({ count: 1 }); await markEscalations({ now: new Date('2026-08-17T07:02:00.000Z') }); expect(mocks.repository.markEscalated).toHaveBeenCalledWith(['s1'], expect.any(Date)) })
  it('allows completion from RUNNING, ESCALATED, and BREACHED', async () => { for (const status of ['RUNNING', 'ESCALATED', 'BREACHED']) { mocks.repository.findInstanceById.mockResolvedValueOnce({ id: 's1', status }); mocks.repository.updateInstance.mockResolvedValueOnce({ id: 's1', status: 'COMPLETED' }); expect((await completeSla({ instanceId: 's1' })).status).toBe('COMPLETED') } })
  it('rejects completion from terminal or invalid states', async () => { for (const status of ['COMPLETED', 'CANCELLED']) { mocks.repository.findInstanceById.mockResolvedValueOnce({ id: 's1', status }); await expect(completeSla({ instanceId: 's1' })).rejects.toThrow(); expect(mocks.repository.updateInstance).not.toHaveBeenCalled() } })
  it('breaches due RUNNING and ESCALATED instances atomically', async () => { mocks.repository.findDueInstances.mockResolvedValue([{ id: 's1' }, { id: 's2' }]); mocks.repository.markBreached.mockResolvedValue({ count: 1 }); expect((await markDueSlas({ now: new Date('2026-08-17T08:00:00.000Z') })).count).toBe(1); expect(mocks.repository.markBreached).toHaveBeenCalledWith(['s1', 's2']) })
  it('claims escalation with an atomic null-escalatedAt guard', async () => { const startedAt = new Date('2026-08-17T07:00:00.000Z'); mocks.repository.findEscalationCandidates.mockResolvedValue([{ id: 's1', startedAt, policy: { escalationSeconds: 60 } }]); mocks.repository.markEscalated.mockResolvedValue({ count: 1 }); expect((await markEscalations({ now: new Date('2026-08-17T07:02:00.000Z') })).count).toBe(1); expect(mocks.repository.markEscalated).toHaveBeenCalledWith(['s1'], expect.any(Date)) })
  it('reports zero when another worker has already claimed the escalation', async () => { const startedAt = new Date('2026-08-17T07:00:00.000Z'); mocks.repository.findEscalationCandidates.mockResolvedValue([{ id: 's1', startedAt, policy: { escalationSeconds: 60 } }]); mocks.repository.markEscalated.mockResolvedValue({ count: 0 }); expect((await markEscalations({ now: new Date('2026-08-17T07:02:00.000Z') })).count).toBe(0) })
  it('starts an SLA with due and warning timestamps derived from the policy', async () => { const startedAt = new Date('2026-08-17T07:00:00.000Z'); mocks.repository.findPolicyByKey.mockResolvedValue({ id: 'p1', durationSeconds: 300, warningSeconds: 120 }); mocks.repository.createInstance.mockResolvedValue({ id: 's1' }); await startSla({ policyKey: 'sla', subjectType: 'CASE', subjectId: 42, startedAt }); expect(mocks.repository.createInstance).toHaveBeenCalledWith(expect.objectContaining({ policyId: 'p1', subjectId: '42', startedAt, warningAt: new Date('2026-08-17T07:02:00.000Z'), dueAt: new Date('2026-08-17T07:05:00.000Z') })) })
})
