import crypto from 'node:crypto'
import dns from 'node:dns'
import net from 'node:net'
import { BadRequestError, ConflictError, NotFoundError } from '../../common/errors/appError.js'
import * as repository from './webhook.repository.js'

const { promises: dnsPromises } = dns
const isPrivateIpv4=(ip)=>{const parts=ip.split('.').map(Number);if(parts.length!==4||parts.some(part=>!Number.isInteger(part)||part<0||part>255))return true;const[a,b]=parts;return a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a===0}
const isPrivateIp=(ip)=>{if(net.isIPv4(ip))return isPrivateIpv4(ip);if(net.isIPv6(ip)){const normalized=ip.toLowerCase();return normalized==='::1'||normalized==='::'||normalized.startsWith('fc')||normalized.startsWith('fd')||normalized.startsWith('fe8')||normalized.startsWith('fe9')||normalized.startsWith('fea')||normalized.startsWith('feb')}return true}
const assertSafeWebhookUrl=async(url)=>{let parsed;try{parsed=new URL(url)}catch{throw new BadRequestError('Webhook URL must be valid.')}if(parsed.protocol!=='https:')throw new BadRequestError('Webhook URL must use HTTPS.');if(parsed.username||parsed.password)throw new BadRequestError('Webhook URL must not contain credentials.');if(parsed.port&&!['443','8443'].includes(parsed.port))throw new BadRequestError('Webhook URL uses a disallowed port.');const hostname=parsed.hostname.replace(/^\[|\]$/g,'').toLowerCase();if(hostname==='localhost'||hostname.endsWith('.localhost')||(net.isIP(hostname)&&isPrivateIp(hostname)))throw new BadRequestError('Webhook URL targets a private or loopback address.');try{const records=await dnsPromises.lookup(hostname,{all:true});if(!records.length||records.some(({address})=>isPrivateIp(address)))throw new BadRequestError('Webhook URL resolves to a private or reserved address.')}catch(error){if(error instanceof BadRequestError)throw error;throw new BadRequestError('Webhook hostname could not be safely resolved.')}return parsed}
const createEndpoint=async({key,name,url,events=[],integrationId=null,secretRef=null,headers=null})=>{if(!key||!name||!url)throw new BadRequestError('Webhook key, name, and URL are required.');await assertSafeWebhookUrl(url);if(!Array.isArray(events)||events.length===0)throw new BadRequestError('A webhook must subscribe to at least one event.');if(await repository.findEndpointByKey(key))throw new ConflictError(`Webhook '${key}' already exists.`);return repository.createEndpoint({key,name,url,events,integrationId,secretRef,headers})}
const makeIdempotencyKey=({endpointId,event,entityType=null,entityId=null,correlationId})=>crypto.createHash('sha256').update(JSON.stringify({endpointId,event,entityType,entityId:entityId==null?null:String(entityId),correlationId})).digest('hex')
const queueEvent=async({event,entityType=null,entityId=null,payload,correlationId=crypto.randomUUID()})=>{if(!event||payload===undefined)throw new BadRequestError('Webhook event and payload are required.');if(typeof correlationId!=='string'||correlationId.length<1||correlationId.length>128)throw new BadRequestError('Webhook correlationId must be a non-empty string of at most 128 characters.');const endpoints=await repository.findActiveEndpointsForEvent(event);if(endpoints.length===0)return[];return repository.runTransaction(async(tx)=>{const deliveries=[];for(const endpoint of endpoints){const idempotencyKey=makeIdempotencyKey({endpointId:endpoint.id,event,entityType,entityId,correlationId});const existing=await repository.findIdempotentDeliveryId(idempotencyKey,tx);if(existing.length){const delivery=await repository.findDeliveryById(existing[0].deliveryId,tx);if(delivery)deliveries.push(delivery);continue}const deliveryId=crypto.randomUUID();const delivery=await repository.createDelivery({id:deliveryId,endpointId:endpoint.id,event,entityType,entityId:entityId==null?null:String(entityId),payload},tx);const claimed=await repository.claimIdempotency(idempotencyKey,deliveryId,tx);if(!claimed.length){await repository.deleteDelivery(deliveryId,tx);const winner=await repository.findIdempotentDeliveryId(idempotencyKey,tx);if(winner.length){const existingDelivery=await repository.findDeliveryById(winner[0].deliveryId,tx);if(existingDelivery)deliveries.push(existingDelivery)}}else deliveries.push(delivery)}return deliveries})}
const signPayload=({payload,secret})=>{if(!secret)throw new BadRequestError('A secret is required to sign a webhook payload.');return crypto.createHmac('sha256',secret).update(JSON.stringify(payload)).digest('hex')}
const markSent=async(deliveryId)=>repository.updateDelivery(deliveryId,{status:'SENT',sentAt:new Date(),attempts:{increment:1},lastError:null})
const markFailed=async(deliveryId,error,nextAttemptAt=null)=>repository.updateDelivery(deliveryId,{status:nextAttemptAt?'QUEUED':'FAILED',attempts:{increment:1},nextAttemptAt,lastError:String(error)})
const getDueDeliveries=async(limit=50)=>repository.findDueDeliveries(Math.min(Math.max(limit,1),100))
const getDelivery=async(id)=>{const delivery=await repository.findDeliveryById(id);if(!delivery)throw new NotFoundError(`Webhook delivery '${id}' was not found.`);return delivery}
export { createEndpoint, queueEvent, signPayload, markSent, markFailed, getDueDeliveries, getDelivery, assertSafeWebhookUrl, makeIdempotencyKey }
