import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

vi.mock('../../../../src/modules/obo/receiving/receiving.repository.js')
vi.mock('../../../../src/platform/workflow/workflow.service.js')

const repository = await import('../../../../src/modules/obo/receiving/receiving.repository.js')
const workflowService = await import('../../../../src/platform/workflow/workflow.service.js')
const service = await import('../../../../src/modules/obo/receiving/receiving.service.js')
const spies = { findApplication: repository.findApplication, findWorkflowInstance: repository.findWorkflowInstance, findSubmissionAppointment: repository.findSubmissionAppointment, findPersonNotificationContext: repository.findPersonNotificationContext, listApplications: repository.listApplications, updateApplication: repository.updateApplication, addDecision: repository.addDecision, withTransaction: repository.withTransaction, transitionWorkflow: workflowService.transitionWorkflow }
afterEach(() => vi.clearAllMocks())
beforeEach(() => { spies.withTransaction.mockImplementation(async (callback) => callback({})); spies.findWorkflowInstance.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'SUBMISSION_SCHEDULED' } }); spies.transitionWorkflow.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'RECEIVING' } }); spies.findPersonNotificationContext.mockResolvedValue(null) })
const scheduled = { id: 'application-1', workflowInstanceId: 'workflow-1', clientPersonId: 'person-1', referenceNumber: 'BP-1', permitType: { name: 'Building Permit' }, submittedAt: null, professional: { status: 'VERIFIED' }, submissionAppointment: { appointmentId: 'appointment-1' } }

describe('OBO receiving service', () => {
  it('lists applications awaiting receiving', async () => { spies.listApplications.mockResolvedValue([{ id: 'application-1', status: 'SUBMISSION_SCHEDULED' }]); await expect(service.listApplications({ status: 'SUBMISSION_SCHEDULED' })).resolves.toEqual([{ id: 'application-1', status: 'SUBMISSION_SCHEDULED' }]) })
  it('receives valid hardcopy submissions through the workflow engine', async () => { spies.findApplication.mockResolvedValueOnce(scheduled).mockResolvedValueOnce({ ...scheduled, submittedAt: new Date() }); spies.findSubmissionAppointment.mockResolvedValue({ status: 'SCHEDULED', slot: { startsAt: new Date(Date.now() - 60000) } }); spies.updateApplication.mockResolvedValue({ id: 'application-1' }); await expect(service.receiveHardcopy({ id: 'application-1', actorId: 'officer-1' })).resolves.toMatchObject({ id: 'application-1' }); expect(spies.transitionWorkflow).toHaveBeenCalledWith(expect.objectContaining({ instanceId: 'workflow-1', transitionKey: 'RECEIVE_HARDCOPY', actorId: 'officer-1' })); expect(spies.updateApplication).toHaveBeenCalledWith('application-1', expect.objectContaining({ submittedAt: expect.any(Date) }), expect.any(Object)) })
  it('rejects invalid receiving conditions', async () => { spies.findApplication.mockResolvedValue(null); await expect(service.receiveHardcopy({ id: 'missing', actorId: 'officer-1' })).rejects.toThrow('not found'); spies.findApplication.mockResolvedValue(scheduled); spies.findWorkflowInstance.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'DRAFT' } }); await expect(service.receiveHardcopy({ id: 'application-1', actorId: 'officer-1' })).rejects.toThrow('Only scheduled applications'); spies.findWorkflowInstance.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'SUBMISSION_SCHEDULED' } }); spies.findApplication.mockResolvedValue({ ...scheduled, submissionAppointment: null }); await expect(service.receiveHardcopy({ id: 'application-1', actorId: 'officer-1' })).rejects.toThrow('appointment is required'); spies.findApplication.mockResolvedValue(scheduled); spies.findSubmissionAppointment.mockResolvedValue(null); await expect(service.receiveHardcopy({ id: 'application-1', actorId: 'officer-1' })).rejects.toThrow('no longer exists'); spies.findSubmissionAppointment.mockResolvedValue({ status: 'CANCELLED', slot: { startsAt: new Date(Date.now() - 60000) } }); await expect(service.receiveHardcopy({ id: 'application-1', actorId: 'officer-1' })).rejects.toThrow('not valid for receiving'); spies.findSubmissionAppointment.mockResolvedValue({ status: 'SCHEDULED', slot: { startsAt: new Date(Date.now() + 60000) } }); await expect(service.receiveHardcopy({ id: 'application-1', actorId: 'officer-1' })).rejects.toThrow('has not started'); spies.findSubmissionAppointment.mockResolvedValue({ status: 'SCHEDULED', slot: { startsAt: new Date(Date.now() - 60000) } }); spies.findApplication.mockResolvedValue({ ...scheduled, professional: { status: 'PENDING_VERIFICATION' } }); await expect(service.receiveHardcopy({ id: 'application-1', actorId: 'officer-1' })).rejects.toThrow('professional is not verified') })
  it('accepts a received application and moves it to inspection', async () => { spies.findApplication.mockResolvedValue({ ...scheduled, submissionAppointment: null }); spies.findWorkflowInstance.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'RECEIVING' } }); spies.transitionWorkflow.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'FOR_INSPECTION' } }); spies.updateApplication.mockResolvedValue({ id: 'application-1' }); spies.addDecision.mockResolvedValue({ id: 'decision-1' }); await expect(service.decide({ id: 'application-1', actorId: 'officer-1', decision: 'ACCEPTED' })).resolves.toMatchObject({ status: 'FOR_INSPECTION' }); expect(spies.transitionWorkflow).toHaveBeenCalledWith(expect.objectContaining({ transitionKey: 'ACCEPT_FOR_INSPECTION' })); expect(spies.addDecision).toHaveBeenCalledWith(expect.objectContaining({ decision: 'ACCEPTED', decidedByUserId: 'officer-1' }), expect.any(Object)) })
  it('declines a received application only with a reason', async () => { spies.findApplication.mockResolvedValue({ ...scheduled, submissionAppointment: null }); spies.findWorkflowInstance.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'RECEIVING' } }); spies.transitionWorkflow.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'DECLINED' } }); spies.updateApplication.mockResolvedValue({ id: 'application-1' }); spies.addDecision.mockResolvedValue({ id: 'decision-1' }); await expect(service.decide({ id: 'application-1', actorId: 'officer-1', decision: 'DECLINED' })).rejects.toThrow('reason is required'); await expect(service.decide({ id: 'application-1', actorId: 'officer-1', decision: 'DECLINED', reason: 'Missing documents' })).resolves.toMatchObject({ status: 'DECLINED' }); expect(spies.transitionWorkflow).toHaveBeenCalledWith(expect.objectContaining({ transitionKey: 'DECLINE' })); expect(spies.addDecision).toHaveBeenCalledWith(expect.objectContaining({ decision: 'DECLINED', reason: 'Missing documents', decidedByUserId: 'officer-1' }), expect.any(Object)) })
})
