import { getQueue, enqueueJob } from '../../infrastructure/queue/bullmq.js'
import { SCHEDULER_TYPES, DEFAULT_SCHEDULER_QUEUE, MAX_SCHEDULER_ID_LENGTH, MAX_JOB_NAME_LENGTH } from './scheduler.constants.js'
const normalizeString=(value,name,maxLength)=>{const normalized=String(value||'').trim();if(!normalized)throw new TypeError(`${name} is required`);if(normalized.length>maxLength)throw new RangeError(`${name} must not exceed ${maxLength} characters`);return normalized}
const normalizeQueue=(queue)=>normalizeString(queue||DEFAULT_SCHEDULER_QUEUE,'queue',100), normalizeSchedulerId=(id)=>normalizeString(id,'schedulerId',MAX_SCHEDULER_ID_LENGTH), normalizeJobName=(name)=>normalizeString(name,'jobName',MAX_JOB_NAME_LENGTH)
const validateEvery=(every)=>{const value=Number(every);if(!Number.isInteger(value)||value<1000)throw new RangeError('every must be an integer number of milliseconds >= 1000');return value}
const validateDelay=(delay)=>{const value=Number(delay);if(!Number.isInteger(value)||value<0)throw new RangeError('delay must be an integer number of milliseconds >= 0');return value}
const validateCron=(pattern)=>{const value=normalizeString(pattern,'cron',100);if(value.split(/\s+/).length<5)throw new RangeError('cron must contain at least 5 fields');return value}
const createSchedulerService=({queueProvider={getQueue,enqueueJob}}={})=>{const scheduleEvery=async({schedulerId,queue=DEFAULT_SCHEDULER_QUEUE,jobName,data={},every,jobOptions={}})=>{const id=normalizeSchedulerId(schedulerId),queueName=normalizeQueue(queue),name=normalizeJobName(jobName),interval=validateEvery(every),targetQueue=await queueProvider.getQueue(queueName);return targetQueue.upsertJobScheduler(id,{every:interval},{name,data,opts:{...jobOptions,removeOnComplete:jobOptions.removeOnComplete??{age:86400,count:1000},removeOnFail:jobOptions.removeOnFail??{age:604800,count:5000}}})};const scheduleCron=async({schedulerId,queue=DEFAULT_SCHEDULER_QUEUE,jobName,data={},cron,jobOptions={}})=>{const id=normalizeSchedulerId(schedulerId),queueName=normalizeQueue(queue),name=normalizeJobName(jobName),pattern=validateCron(cron),targetQueue=await queueProvider.getQueue(queueName);return targetQueue.upsertJobScheduler(id,{pattern},{name,data,opts:{...jobOptions,removeOnComplete:jobOptions.removeOnComplete??{age:86400,count:1000},removeOnFail:jobOptions.removeOnFail??{age:604800,count:5000}}})};const scheduleOnce=async({schedulerId,queue=DEFAULT_SCHEDULER_QUEUE,jobName,data={},delay,jobOptions={}})=>{const id=normalizeSchedulerId(schedulerId),queueName=normalizeQueue(queue),name=normalizeJobName(jobName),delayMs=validateDelay(delay);return queueProvider.enqueueJob(queueName,name,data,{...jobOptions,jobId:id,delay:delayMs,removeOnComplete:jobOptions.removeOnComplete??{age:86400,count:1000},removeOnFail:jobOptions.removeOnFail??{age:604800,count:5000}})};const removeSchedule=async({schedulerId,queue=DEFAULT_SCHEDULER_QUEUE})=>{const id=normalizeSchedulerId(schedulerId),queueName=normalizeQueue(queue),targetQueue=await queueProvider.getQueue(queueName);return targetQueue.removeJobScheduler(id)};const listSchedules=async({queue=DEFAULT_SCHEDULER_QUEUE,start=0,end=99}={})=>{const queueName=normalizeQueue(queue),targetQueue=await queueProvider.getQueue(queueName);return targetQueue.getJobSchedulers(start,end)};return{scheduleEvery,scheduleCron,scheduleOnce,removeSchedule,listSchedules,types:SCHEDULER_TYPES}}
const scheduler=createSchedulerService()
export { createSchedulerService, scheduler, scheduleEvery, scheduleCron, scheduleOnce, removeSchedule, listSchedules }
