import { ConflictError, NotFoundError, ValidationError } from '../../../common/errors/appError.js'
import { clearRolePermissionCache } from '../../../platform/authorization/authorization.service.js'
import * as repository from './authorization-management.repository.js'
const PREFIX='cadenza_'
const assertModule=async(id)=>{const m=await repository.findModuleById(id);if(!m||!m.key.startsWith(PREFIX))throw new NotFoundError('Cadenza authorization module not found.');return m}
const listModules=()=>repository.listModules()
const getModule=(id)=>assertModule(id)
const createModule=async({key,name,description})=>{if(!key.startsWith(PREFIX))throw new ValidationError('Authorization module key must start with cadenza_.');if(await repository.findModuleByKey(key))throw new ConflictError(`Module '${key}' already exists.`);return repository.createModule({key,name,description})}
const addPermission=async({moduleId,action})=>{const m=await assertModule(moduleId);if(m.permissions.some(p=>p.action===action))throw new ConflictError(`Permission '${action}' already exists for this module.`);return repository.createPermission({moduleId:m.id,action})}
const setModuleActive=async({moduleId,isActive})=>{const m=await assertModule(moduleId);if(!isActive&&m.key===PREFIX+'authorization')throw new ValidationError('The authorization module cannot be disabled.');const updated=await repository.setModuleActive(m.id,isActive);for(const {roleId} of await repository.listRoleIdsByModuleId(m.id))await clearRolePermissionCache(roleId);return updated}
const listRoles=({appId})=>repository.listRoles(appId)
const createRole=async({appId,membershipId,name,description})=>{if(!(await repository.findMembershipById(membershipId,appId)))throw new NotFoundError('Application membership not found.');try{return await repository.createRole({appId,name,description,membershipId})}catch(e){if(e?.code==='P2002')throw new ConflictError(`Role '${name}' already exists in the current application.`);throw e}}
const getRole=async({roleId,appId})=>{const role=await repository.findRoleForApp(roleId,appId);if(!role)throw new NotFoundError('Role not found in the current application.');return repository.findRoleById(role.id,appId)}
const getMembership=async({membershipId,appId})=>{const m=await repository.findMembershipById(membershipId,appId);if(!m)throw new NotFoundError('Application membership not found.');return m}
const replaceRolePermissions=async({roleId,permissionIds,appId})=>{if(!(await repository.findRoleForApp(roleId,appId)))throw new NotFoundError('Role not found in the current application.');const ids=[...new Set(permissionIds.map(Number))];const ps=await Promise.all(ids.map(id=>repository.findPermissionById(id)));if(ps.some(p=>!p))throw new NotFoundError('One or more permissions were not found.');if(ps.some(p=>!p.module.isActive))throw new ValidationError('Permissions from inactive modules cannot be assigned.');if(ps.some(p=>!p.module.key.startsWith(PREFIX)))throw new ValidationError('A role can only contain permissions from Cadenza authorization modules.');const result=await repository.replaceRolePermissions(roleId,appId,ids);if(result===undefined)throw new ValidationError('One or more permissions do not belong to Cadenza authorization modules.');if(result===null)throw new NotFoundError('Role not found in the current application.');await clearRolePermissionCache(roleId);return result}
const listMembershipRoles=({membershipId,appId})=>repository.listMembershipRoles(membershipId,appId)
const replaceMembershipRoles=async({membershipId,appId,roleIds})=>{if(!(await repository.findMembershipById(membershipId,appId)))throw new NotFoundError('Application membership not found.');const result=await repository.replaceMembershipRoles(membershipId,appId,[...new Set(roleIds.map(Number))]);if(result===undefined)throw new ValidationError('One or more roles do not belong to the current application.');if(result===null)throw new NotFoundError('Application membership not found.');return result}
export {PREFIX as CADENZA_AUTHORIZATION_MODULE_PREFIX,listModules,getModule,createModule,addPermission,setModuleActive,listRoles,createRole,getRole,getMembership,replaceRolePermissions,listMembershipRoles,replaceMembershipRoles}
