const express = require('express')
const { asyncHandler, validate, idempotency } = require('../../common/middleware')
const authenticate = require('../../features/auth/authenticate.secure')
const authorize = require('../../platform/authorization/authorize')
const { ACCESS_CONTROL_MODULES, ACCESS_CONTROL_ACTIONS } = require('../../platform/authorization/access-control.constants')
const controller = require('./obo.controller')
const validation = require('./obo.validation')
const router = express.Router()
const requireIdempotency = idempotency({ scope: 'obo', required: true })
const applicationsRead = authorize(ACCESS_CONTROL_MODULES.APPLICATIONS, ACCESS_CONTROL_ACTIONS.READ)
const applicationsCreate = authorize(ACCESS_CONTROL_MODULES.APPLICATIONS, ACCESS_CONTROL_ACTIONS.CREATE)
const applicationsReview = authorize(ACCESS_CONTROL_MODULES.APPLICATIONS, ACCESS_CONTROL_ACTIONS.REVIEW)
const applicationsReceive = authorize(ACCESS_CONTROL_MODULES.APPLICATIONS, ACCESS_CONTROL_ACTIONS.RECEIVE)

router.get('/permit-types', authenticate, applicationsRead, asyncHandler(controller.listPermitTypes))
router.post('/professionals', authenticate, applicationsReview, requireIdempotency, validate(validation.createProfessionalValidator), asyncHandler(controller.createProfessional))
router.get('/receiving/professionals', authenticate, applicationsReview, asyncHandler(controller.listPendingProfessionals))
router.post('/professionals/:id/verification', authenticate, applicationsReview, requireIdempotency, validate(validation.verifyProfessionalValidator), asyncHandler(controller.verifyProfessional))
router.post('/applications', authenticate, applicationsCreate, requireIdempotency, validate(validation.createApplicationValidator), asyncHandler(controller.createApplication))
router.get('/applications/mine', authenticate, applicationsRead, asyncHandler(controller.listMine))
router.get('/applications/:id', authenticate, applicationsRead, validate(validation.applicationValidator), asyncHandler(controller.getApplication))
router.post('/applications/:id/submit', authenticate, applicationsCreate, requireIdempotency, validate(validation.applicationValidator), asyncHandler(controller.submitApplication))
router.post('/applications/:id/submission-appointment', authenticate, applicationsCreate, requireIdempotency, validate(validation.submissionAppointmentValidator), asyncHandler(controller.bookSubmissionAppointment))
router.get('/receiving/applications', authenticate, applicationsReceive, validate(validation.receivingListValidator), asyncHandler(controller.listReceivingApplications))
router.post('/receiving/applications/:id/decision', authenticate, applicationsReceive, requireIdempotency, validate(validation.receivingDecisionValidator), asyncHandler(controller.receiveApplication))
module.exports = router
