import { beforeEach, describe, expect, it, vi } from 'vitest'

const repository = vi.hoisted(() => ({ findPersonByUserId: vi.fn(), findById: vi.fn(), findOwnedByClient: vi.fn(), listByClient: vi.fn(), create: vi.fn(), update: vi.fn(), findPersonNotificationContext: vi.fn(), withTransaction: vi.fn(), listByApplicationId: vi.fn(), findByApplicationAndCaseRequirement: vi.fn(), createMany: vi.fn() }))
const permitTypeService = vi.hoisted(() => ({ getPermitTypeById: vi.fn(), getRequirementIds: vi.fn() }))
const requirementService = vi.hoisted(() => ({ attachDefinitionsToCase: vi.fn(), listForCase: vi.fn(), updateStatus: vi.fn() }))
const caseService = vi.hoisted(() => ({ getOrCreateType: vi.fn(), createRecord: vi.fn() }))
const participantService = vi.hoisted(() => ({ add: vi.fn(), list: vi.fn(), remove: vi.fn() }))
const professionalService = vi.hoisted(() => ({ getForReference: vi.fn() }))
const professionalReferenceService = vi.hoisted(() => ({ validateProfessionalReferences: vi.fn(), buildProfessionalSnapshots: vi.fn() }))
const formService = vi.hoisted(() => ({ getFormById: vi.fn(), getFormVersionById: vi.fn(), validateFormValues: vi.fn() }))
const workflowService = vi.hoisted(() => ({ getWorkflowInstance: vi.fn(), startWorkflow: vi.fn(), transitionWorkflow: vi.fn() }))
const auditService = vi.hoisted(() => ({ recordAudit: vi.fn() }))
const eventBus = vi.hoisted(() => ({ publish: vi.fn() }))
const appointmentService = vi.hoisted(() => ({ getAppointmentForReference: vi.fn() }))
const taskService = vi.hoisted(() => ({ create: vi.fn(), list: vi.fn(), update: vi.fn() }))
const documentsService = vi.hoisted(() => ({ getOwnedDocument: vi.fn() }))

vi.mock('../../../src/modules/obo/plan-permits/plan-permit.repository.js', () => repository)
vi.mock('../../../src/modules/obo/permit-types/permit-type.service.js', () => permitTypeService)
vi.mock('../../../src/modules/obo/permit-types/permit-type-requirement.service.js', () => ({ getRequirementIds: permitTypeService.getRequirementIds }))
vi.mock('../../../src/features/requirements/requirements.service.js', () => requirementService)
vi.mock('../../../src/features/cases/cases.service.js', () => caseService)
vi.mock('../../../src/features/participants/participants.service.js', () => ({ default: participantService }))
vi.mock('../../../src/modules/obo/professionals/professional.service.js', () => professionalService)
vi.mock('../../../src/modules/obo/professionals/professional-reference.service.js', () => professionalReferenceService)
vi.mock('../../../src/platform/forms/form.service.js', () => formService)
vi.mock('../../../src/platform/workflow/workflow.service.js', () => workflowService)
vi.mock('../../../src/platform/audit/audit.service.js', () => auditService)
vi.mock('../../../src/platform/event-bus/event-bus.js', () => eventBus)
vi.mock('../../../src/features/appointments/appointment.service.js', () => appointmentService)
vi.mock('../../../src/features/tasks/tasks.service.js', () => taskService)
vi.mock('../../../src/features/documents/document.service.js', () => documentsService)
vi.mock('../../../src/modules/obo/application-documents/application-document.repository.js', () => repository)

const service = await import('../../../src/modules/obo/plan-permits/plan-permit.service.js')
const { resolveAndValidateForm } = await import('../../../src/modules/obo/plan-permits/plan-permit.form.js')
const { createApplicationValidator, updateApplicationValidator } = await import('../../../src/modules/obo/plan-permits/plan-permit.validation.js')
const documentService = await import('../../../src/modules/obo/application-documents/application-document.service.js')

const person = { id: 'person-1', userId: 'user-1', email: 'client@example.com' }
const permitType = { id: 'permit-1', name: 'Building Permit', isActive: true, formId: null }

beforeEach(() => {
  vi.clearAllMocks(); repository.withTransaction.mockImplementation(async (callback) => callback({ tx: true })); repository.findPersonByUserId.mockResolvedValue(person); repository.findOwnedByClient.mockResolvedValue({ id: 'application-1', caseId: 'case-1', workflowInstanceId: 'workflow-1', clientPersonId: 'person-1', permitType, formValues: {}, submissionAppointment: { appointmentId: 'appointment-1' } }); repository.findById.mockResolvedValue({ id: 'application-1', caseId: 'case-1', caseRecord: { id: 'case-1' }, workflowInstanceId: 'workflow-1', clientPersonId: 'person-1', permitType }); permitTypeService.getPermitTypeById.mockResolvedValue(permitType); permitTypeService.getRequirementIds.mockResolvedValue(['requirement-1', 'requirement-2']); requirementService.attachDefinitionsToCase.mockResolvedValue([]); caseService.getOrCreateType.mockResolvedValue({ id: 'case-type-1', key: 'obo-permit-application' }); caseService.createRecord.mockResolvedValue({ id: 'case-1', caseNumber: 'CASE-20260910-ABC12345' }); participantService.add.mockResolvedValue({ id: 'participant-1' }); professionalService.getForReference.mockResolvedValue({ id: 'professional-1', personId: 'professional-person-1', professionalRole: 'ARCHITECT' }); repository.create.mockResolvedValue({ id: 'application-1', referenceNumber: 'OBO-20260910-ABC12345', status: 'DRAFT', permitType, workflowInstanceId: 'workflow-1', caseId: 'case-1' }); repository.update.mockResolvedValue({ id: 'application-1', workflowInstanceId: 'workflow-1', status: 'DRAFT', permitType, caseId: 'case-1' }); workflowService.getWorkflowInstance.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'DRAFT' } }); workflowService.startWorkflow.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'DRAFT' } }); workflowService.transitionWorkflow.mockResolvedValue({ id: 'workflow-1' }); formService.getFormById.mockResolvedValue({ id: 'form-1', key: 'building-permit', isActive: true }); formService.getFormVersionById.mockResolvedValue({ id: 'form-version-1', formId: 'form-1', version: 1, status: 'PUBLISHED', fields: [] }); formService.validateFormValues.mockResolvedValue({ valid: true, formVersionId: 'form-version-1' }); appointmentService.getAppointmentForReference.mockResolvedValue({ id: 'appointment-1', status: 'SCHEDULED' }); taskService.create.mockResolvedValue({ id: 'task-1' }); eventBus.publish.mockResolvedValue(undefined); professionalReferenceService.validateProfessionalReferences.mockResolvedValue(true); professionalReferenceService.buildProfessionalSnapshots.mockResolvedValue({ architect: { professionalId: 'professional-a', name: 'John Doe', registrationNumber: 'REG-1', prcId: 'PRC-1', ptrNumber: 'PTR-1', role: 'ARCHITECT' } })
})

describe('OBO plan permit service', () => {
  it('creates a draft through Permit Type, Case, requirements, and Participant service boundaries', async () => { await expect(service.createApplication({ userId: 'user-1', permitTypeId: 'permit-1', formValues: { projectAddress: 'Manila' } })).resolves.toMatchObject({ id: 'application-1', status: 'DRAFT', workflowInstanceId: 'workflow-1' }); expect(permitTypeService.getPermitTypeById).toHaveBeenCalledWith('permit-1'); expect(permitTypeService.getRequirementIds).toHaveBeenCalledWith('permit-1', expect.anything()); expect(requirementService.attachDefinitionsToCase).toHaveBeenCalledWith(expect.objectContaining({ caseId: 'case-1', requirementIds: ['requirement-1', 'requirement-2'], metadata: { source: 'obo-plan-permit', permitTypeId: 'permit-1' }, db: expect.anything() })); expect(caseService.createRecord).toHaveBeenCalledWith(expect.objectContaining({ caseTypeId: 'case-type-1', title: 'Building Permit Application', status: 'OPEN', createdByUserId: 'user-1' }), { db: expect.anything() }); expect(caseService.createRecord.mock.calls[0][0]).not.toHaveProperty('caseNumber'); expect(repository.create).toHaveBeenCalledWith(expect.objectContaining({ caseId: 'case-1', permitTypeId: 'permit-1' }), expect.anything()); expect(participantService.add).toHaveBeenCalledWith(expect.objectContaining({ caseId: 'case-1', personId: 'person-1', roleKey: 'APPLICANT', isPrimary: true, db: expect.anything() })); expect(eventBus.publish).toHaveBeenCalledWith(expect.objectContaining({ event: 'obo.permit_application.created', entityType: 'OboPermitApplication', entityId: 'application-1', db: expect.anything() })) })
  it('rejects a missing Permit Type before persistence', async () => { permitTypeService.getPermitTypeById.mockResolvedValue(null); await expect(service.createApplication({ userId: 'user-1', permitTypeId: 'missing', formValues: {} })).rejects.toThrow('Active permit type not found'); expect(repository.create).not.toHaveBeenCalled(); expect(caseService.createRecord).not.toHaveBeenCalled() })
  it('uses Platform Workflow and Appointment services for hydration', async () => { await service.getMine({ id: 'application-1', userId: 'user-1' }); expect(workflowService.getWorkflowInstance).toHaveBeenCalledWith('workflow-1'); expect(appointmentService.getAppointmentForReference).toHaveBeenCalledWith({ id: 'appointment-1', db: undefined }) })
  it('associates verified professionals from form references as case participants', async () => { professionalReferenceService.buildProfessionalSnapshots.mockResolvedValue({ architect: { professionalId: 'professional-1', name: 'John Doe', professionalRole: 'ARCHITECT' }, engineers: [{ professionalId: 'professional-2', name: 'Jane Doe', professionalRole: 'CIVIL_ENGINEER' }, { professionalId: 'professional-1', name: 'John Doe', professionalRole: 'ARCHITECT' }] }); professionalService.getForReference.mockResolvedValueOnce({ id: 'professional-1', personId: 'professional-person-1', professionalRole: 'ARCHITECT' }).mockResolvedValueOnce({ id: 'professional-2', personId: 'professional-person-2', professionalRole: 'CIVIL_ENGINEER' }).mockResolvedValueOnce({ id: 'professional-1', personId: 'professional-person-1', professionalRole: 'ARCHITECT' }); repository.findOwnedByClient.mockResolvedValue({ id: 'application-1', caseId: 'case-1', workflowInstanceId: 'workflow-1', clientPersonId: 'person-1', permitType: { ...permitType, formId: 'form-1' }, formVersionId: 'form-version-1', formVersion: { id: 'form-version-1', formId: 'form-1', version: 1, fields: [] }, formValues: { architect: 'professional-1', engineers: ['professional-2', 'professional-1'] }, submissionAppointment: null }); await service.submit({ id: 'application-1', userId: 'user-1' }); expect(participantService.add).toHaveBeenCalledWith(expect.objectContaining({ caseId: 'case-1', personId: 'professional-person-1', roleKey: 'PROFESSIONAL', db: expect.anything() })); expect(participantService.add).toHaveBeenCalledWith(expect.objectContaining({ caseId: 'case-1', personId: 'professional-person-2', roleKey: 'PROFESSIONAL', db: expect.anything() })); expect(participantService.add.mock.calls.filter(([args]) => args.roleKey === 'PROFESSIONAL')).toHaveLength(2); expect(eventBus.publish).toHaveBeenCalledWith(expect.objectContaining({ event: 'obo.permit_application.professional.associated', entityId: 'application-1', db: expect.anything() })) })
  it('does not expose Receiving decision persistence from the Plan Permit repository', () => { expect(repository).not.toHaveProperty('addDecision') })
})

describe('OBO plan permit form resolution', () => {
  it('resolves an explicitly selected published version instead of the latest version', async () => { formService.getFormVersionById.mockResolvedValue({ id: 'form-version-2', formId: 'form-1', version: 2, status: 'PUBLISHED' }); await expect(resolveAndValidateForm({ permitType: { id: 'permit-1', formId: 'form-1' }, formVersionId: 'form-version-2', formValues: { floorArea: 120 } })).resolves.toEqual({ formVersionId: 'form-version-2' }); expect(formService.getFormById).toHaveBeenCalledWith('form-1'); expect(formService.getFormVersionById).toHaveBeenCalledWith('form-version-2'); expect(formService.validateFormValues).toHaveBeenCalledWith({ formKey: 'building-permit', version: 2, values: { floorArea: 120 }, requireRequired: false }) })
  it('returns field validation errors to the API error response', async () => { const errors = [{ field: 'floorArea', code: 'VALIDATION', message: 'Floor Area must be greater than 0.' }, { field: 'projectAddress', code: 'REQUIRED', message: 'Project Address is required.' }]; formService.validateFormValues.mockResolvedValue({ valid: false, errors }); await expect(resolveAndValidateForm({ permitType: { id: 'permit-1', formId: 'form-1' }, formVersionId: 'form-version-2', formValues: {} })).rejects.toMatchObject({ statusCode: 422, errors, message: 'Permit form validation failed.' }) })
  it('rejects a stored version that does not belong to the permit type form', async () => { formService.getFormVersionById.mockResolvedValue({ id: 'form-version-2', formId: 'different-form', version: 2, status: 'PUBLISHED' }); await expect(resolveAndValidateForm({ permitType: { id: 'permit-1', formId: 'form-1' }, formVersionId: 'form-version-2', formValues: {} })).rejects.toThrow('selected form version is not a published version for this permit type'); expect(formService.validateFormValues).not.toHaveBeenCalled() })
  it('rejects a stored version that is not published', async () => { formService.getFormVersionById.mockResolvedValue({ id: 'form-version-2', formId: 'form-1', version: 2, status: 'DRAFT' }); await expect(resolveAndValidateForm({ permitType: { id: 'permit-1', formId: 'form-1' }, formVersionId: 'form-version-2', formValues: {} })).rejects.toThrow('selected form version is not a published version for this permit type'); expect(formService.validateFormValues).not.toHaveBeenCalled() })
})

describe('OBO plan permit application validation', () => {
  const uuid = '00000000-0000-4000-8000-000000000001'; const request = (body, params = {}) => ({ body, params })
  it('accepts form-based professional references without a top-level professionalId', async () => { const result = await createApplicationValidator(request({ permitTypeId: uuid, formVersionId: uuid, formValues: { architect: uuid, civilEngineer: [uuid] } })); expect(result.body).toEqual({ permitTypeId: uuid, formVersionId: uuid, formValues: { architect: uuid, civilEngineer: [uuid] } }); expect(result.body).not.toHaveProperty('professionalId') })
  it('rejects the legacy professionalId on application creation', async () => { await expect(createApplicationValidator(request({ permitTypeId: uuid, professionalId: uuid, formValues: {} }))).rejects.toThrow() })
  it('requires permitTypeId and formValues when creating an application', async () => { await expect(createApplicationValidator(request({ formValues: {} }))).rejects.toThrow(); await expect(createApplicationValidator(request({ permitTypeId: uuid }))).rejects.toThrow() })
  it('accepts draft updates using formValues and an optional form version', async () => { const result = await updateApplicationValidator(request({ formVersionId: uuid, formValues: { architect: uuid } }, { id: uuid })); expect(result.body).toEqual({ formVersionId: uuid, formValues: { architect: uuid } }); expect(result.body).not.toHaveProperty('professionalId') })
  it('rejects the legacy professionalId on draft updates', async () => { await expect(updateApplicationValidator(request({ professionalId: uuid, formValues: {} }, { id: uuid }))).rejects.toThrow() })
})

describe('OBO application document checklist', () => {
  const application = { id: 'application-1', referenceNumber: 'OBO-0001', status: 'RECEIVING', caseId: 'case-1', caseRecord: { id: 'case-1' } }; const requirements = [{ id: 'case-requirement-1', requirementId: 'requirement-1', requirement: { id: 'requirement-1', name: 'Building Plan', metadata: { required: true } } }, { id: 'case-requirement-2', requirementId: 'requirement-2', requirement: { id: 'requirement-2', name: 'Site Plan', metadata: { required: false } } }]
  beforeEach(() => { requirementService.listForCase.mockResolvedValue(requirements); requirementService.updateStatus.mockResolvedValue({ id: 'case-requirement-1', status: 'SUBMITTED' }); documentsService.getOwnedDocument.mockResolvedValue({ id: 'document-1', originalName: 'building-plan.pdf' }); repository.createMany.mockResolvedValue({ count: requirements.length }); repository.listByApplicationId.mockResolvedValue([]); repository.findByApplicationAndCaseRequirement.mockResolvedValue({ id: 'receipt-1', caseRequirementId: 'case-requirement-1', status: documentService.STATUS.PENDING, documentId: null, document: null, notes: null }); repository.update.mockResolvedValue({ id: 'receipt-1', caseRequirementId: 'case-requirement-1', status: documentService.STATUS.RECEIVED, documentId: 'document-1', document: { id: 'document-1' } }); repository.withTransaction.mockImplementation(async (callback) => callback('tx')); auditService.recordAudit.mockResolvedValue(undefined); eventBus.publish.mockResolvedValue(undefined); workflowService.getWorkflowInstance.mockResolvedValue({ id: 'workflow-1', currentStep: { key: 'RECEIVING' } }) })
  it('builds the checklist from the case requirements owned by the shared requirements feature', async () => { await documentService.getChecklist({ applicationId: application.id }); expect(requirementService.listForCase).toHaveBeenCalledWith(application.caseRecord.id, undefined); expect(repository.createMany).toHaveBeenCalledWith([{ applicationId: application.id, caseRequirementId: 'case-requirement-1', status: documentService.STATUS.PENDING }, { applicationId: application.id, caseRequirementId: 'case-requirement-2', status: documentService.STATUS.PENDING }], undefined) })
  it('receives a shared document, updates the case requirement fulfillment, records audit, and emits an event', async () => { const result = await documentService.updateReceiptStatus({ applicationId: application.id, requirementId: 'case-requirement-1', actorId: 42, status: documentService.STATUS.RECEIVED, documentId: 'document-1', notes: 'Physical copy checked.' }); expect(documentsService.getOwnedDocument).toHaveBeenCalledWith({ userId: 42, id: 'document-1' }); expect(repository.update).toHaveBeenCalledWith('receipt-1', expect.objectContaining({ status: documentService.STATUS.RECEIVED, documentId: 'document-1', notes: 'Physical copy checked.', receivedByUserId: 42 }), 'tx'); expect(requirementService.updateStatus).toHaveBeenCalledWith(expect.objectContaining({ id: 'case-requirement-1', status: 'SUBMITTED', db: 'tx' })); expect(result.status).toBe(documentService.STATUS.RECEIVED) })
  it('emits a verified event when a received document is verified', async () => { repository.findByApplicationAndCaseRequirement.mockResolvedValue({ id: 'receipt-1', caseRequirementId: 'case-requirement-1', status: documentService.STATUS.RECEIVED, documentId: 'document-1', document: { id: 'document-1' }, notes: null }); repository.update.mockResolvedValue({ id: 'receipt-1', caseRequirementId: 'case-requirement-1', status: documentService.STATUS.VERIFIED, documentId: 'document-1', document: { id: 'document-1' } }); requirementService.updateStatus.mockResolvedValue({ id: 'case-requirement-1', status: 'VERIFIED' }); await documentService.updateReceiptStatus({ applicationId: application.id, requirementId: 'case-requirement-1', actorId: 42, status: documentService.STATUS.VERIFIED }); expect(eventBus.publish).toHaveBeenCalledWith(expect.objectContaining({ event: 'obo.permit_application.document.verified', entityId: 'receipt-1', db: 'tx' })) })
  it('rejects inspection acceptance when a required document is not verified', async () => { await expect(documentService.validateRequiredDocuments({ applicationId: application.id })).rejects.toThrow(/Building Plan/) })
  it('passes required-document validation after all required documents are verified', async () => { repository.listByApplicationId.mockResolvedValue([{ caseRequirementId: 'case-requirement-1', status: documentService.STATUS.VERIFIED }, { caseRequirementId: 'case-requirement-2', status: documentService.STATUS.PENDING }]); await expect(documentService.validateRequiredDocuments({ applicationId: application.id })).resolves.toBe(true) })
})
