import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const repository = await import('../../../src/modules/obo/professionals/professional.repository.js')
const peopleService = await import('../../../src/features/people/people.service.js')
const eventBus = await import('../../../src/platform/event-bus/event-bus.js')
const formService = await import('../../../src/platform/forms/form.service.js')
const professionalService = await import('../../../src/modules/obo/professionals/professional.service.js')
const referenceService = await import('../../../src/modules/obo/professionals/professional-reference.service.js')

const spies = {
  findPersonByUserId: vi.spyOn(repository, 'findPersonByUserId'), findPersonById: vi.spyOn(repository, 'findPersonById'), findByPersonId: vi.spyOn(repository, 'findByPersonId'), findByUserId: vi.spyOn(repository, 'findByUserId'), findById: vi.spyOn(repository, 'findById'), create: vi.spyOn(repository, 'create'), listPending: vi.spyOn(repository, 'listPending'), listVerified: vi.spyOn(repository, 'listVerified'), update: vi.spyOn(repository, 'update'), addDecision: vi.spyOn(repository, 'addDecision'), withTransaction: vi.spyOn(repository, 'withTransaction'),
  peopleGetByUserId: vi.spyOn(peopleService, 'getByUserId'), peopleCreate: vi.spyOn(peopleService, 'create'), peopleUpdate: vi.spyOn(peopleService, 'update'), publish: vi.spyOn(eventBus, 'publish'),
  evaluateCondition: vi.spyOn(formService, 'evaluateCondition'), getForReference: vi.spyOn(professionalService, 'getForReference'),
}

beforeEach(() => {
  vi.clearAllMocks()
  spies.withTransaction.mockImplementation(async (callback) => callback({ name: 'transaction' }))
  spies.evaluateCondition.mockReturnValue(true)
})
afterEach(() => vi.clearAllMocks())

describe('professional verification service', () => {
  it('applies for verification with PRC and PTR credentials and generates a registration number', async () => {
    spies.findPersonByUserId.mockResolvedValue({ id: 'person-1' }); spies.findByPersonId.mockResolvedValue(null); spies.create.mockResolvedValue({ id: 'professional-1', status: 'PENDING_VERIFICATION' })
    await expect(professionalService.applyForVerification({ userId: 'user-1', prcId: '  PRC-123  ', ptrNumber: '  PTR-2026-123  ' })).resolves.toMatchObject({ status: 'PENDING_VERIFICATION' })
    expect(spies.create).toHaveBeenCalledWith(expect.objectContaining({ personId: 'person-1', userId: 'user-1', prcId: 'PRC-123', ptrNumber: 'PTR-2026-123', registrationNumber: expect.stringMatching(/^PRO-\d{8}-[A-F0-9]{8}$/) }))
  })
  it('rejects invalid or duplicate verification applications', async () => {
    await expect(professionalService.applyForVerification({ userId: 'user-1', prcId: ' ', ptrNumber: 'PTR-123' })).rejects.toThrow('prcId is required.')
    await expect(professionalService.applyForVerification({ userId: 'user-1', prcId: 'PRC-123', ptrNumber: ' ' })).rejects.toThrow('ptrNumber is required.')
    spies.findPersonByUserId.mockResolvedValue(null); await expect(professionalService.applyForVerification({ userId: 'user-1', prcId: 'PRC-123', ptrNumber: 'PTR-123' })).rejects.toThrow('does not have a person profile')
    spies.findPersonByUserId.mockResolvedValue({ id: 'person-1' }); spies.findByPersonId.mockResolvedValue({ id: 'professional-1' }); await expect(professionalService.applyForVerification({ userId: 'user-1', prcId: 'PRC-123', ptrNumber: 'PTR-123' })).rejects.toThrow('already exists')
  })
  it('returns the authenticated professional verification record', async () => { spies.findByUserId.mockResolvedValue({ id: 'professional-1', status: 'VERIFIED', prcId: 'PRC-123', ptrNumber: 'PTR-123' }); await expect(professionalService.getMine({ userId: 'user-1' })).resolves.toMatchObject({ id: 'professional-1', status: 'VERIFIED' }); expect(spies.findByUserId).toHaveBeenCalledWith('user-1') })
  it('rejects a professional from deciding their own application', async () => { spies.findById.mockResolvedValue({ id: 'professional-1', userId: 1, status: 'PENDING_VERIFICATION' }); await expect(professionalService.decideVerification({ id: 'professional-1', actorId: 1, decision: 'ACCEPTED' })).rejects.toThrow('cannot approve or decline their own application'); expect(spies.update).not.toHaveBeenCalled(); expect(spies.addDecision).not.toHaveBeenCalled(); expect(spies.publish).not.toHaveBeenCalled() })
  it('records an accepted verification decision transactionally', async () => {
    spies.findById.mockResolvedValue({ id: 'professional-1', userId: 2, personId: 'person-1', status: 'PENDING_VERIFICATION', registrationNumber: 'REG-123', prcId: 'PRC-123', ptrNumber: 'PTR-123', professionalRole: 'ARCHITECT' }); spies.update.mockResolvedValue({ id: 'professional-1', status: 'VERIFIED', verifiedAt: new Date('2026-08-17T07:00:00.000Z') }); spies.addDecision.mockResolvedValue({ id: 'decision-1' }); spies.findPersonById.mockResolvedValue({ userId: 2, email: 'professional@example.com' }); spies.publish.mockResolvedValue({ id: 'event-1' })
    await expect(professionalService.decideVerification({ id: 'professional-1', actorId: 3, decision: 'ACCEPTED' })).resolves.toMatchObject({ status: 'VERIFIED' }); expect(spies.update).toHaveBeenCalledWith('professional-1', expect.objectContaining({ status: 'VERIFIED', verifiedByUserId: 3 }), expect.anything()); expect(spies.addDecision).toHaveBeenCalled(); expect(spies.publish).toHaveBeenCalledWith(expect.objectContaining({ db: expect.anything(), event: 'obo.professional.verification.decided' }))
  })
  it('requires a reason when declining professional verification', async () => { spies.findById.mockResolvedValue({ id: 'professional-1', status: 'PENDING_VERIFICATION' }); await expect(professionalService.decideVerification({ id: 'professional-1', actorId: 'officer-1', decision: 'DECLINED' })).rejects.toThrow('reason is required') })
  it('rejects unknown or already-decided professionals', async () => { spies.findById.mockResolvedValue(null); await expect(professionalService.decideVerification({ id: 'missing', actorId: 'officer-1', decision: 'ACCEPTED' })).rejects.toThrow('not found'); spies.findById.mockResolvedValue({ id: 'professional-1', status: 'VERIFIED' }); await expect(professionalService.decideVerification({ id: 'professional-1', actorId: 'officer-1', decision: 'DECLINED', reason: 'Invalid credentials' })).rejects.toThrow('not awaiting verification') })
})

describe('professional person profile workflow', () => {
  it('retrieves the authenticated user person profile through the shared people feature', async () => { spies.peopleGetByUserId.mockResolvedValue({ id: 'person-1', userId: 7 }); await expect(professionalService.getProfile({ userId: 7 })).resolves.toMatchObject({ id: 'person-1', userId: 7 }); expect(spies.peopleGetByUserId).toHaveBeenCalledWith(7) })
  it('creates the person profile independently when no profile exists', async () => { spies.findPersonByUserId.mockResolvedValue(null); spies.peopleCreate.mockResolvedValue({ id: 'person-1', userId: 7 }); await expect(professionalService.createProfile({ userId: 7, firstName: 'Jane', lastName: 'Doe' })).resolves.toMatchObject({ id: 'person-1', userId: 7 }); expect(spies.peopleCreate).toHaveBeenCalledWith({ userId: 7, firstName: 'Jane', lastName: 'Doe' }) })
  it('rejects profile creation when a person profile already exists', async () => { spies.findPersonByUserId.mockResolvedValue({ id: 'person-1', userId: 7 }); await expect(professionalService.createProfile({ userId: 7, firstName: 'Jane', lastName: 'Doe' })).rejects.toThrow('Professional person profile already exists.'); expect(spies.peopleCreate).not.toHaveBeenCalled() })
  it('updates the existing person profile without creating a duplicate', async () => { spies.findPersonByUserId.mockResolvedValue({ id: 'person-1', userId: 7 }); spies.peopleUpdate.mockResolvedValue({ id: 'person-1', userId: 7, firstName: 'Jane', lastName: 'Doe' }); await expect(professionalService.updateProfile({ userId: 7, firstName: 'Jane', lastName: 'Doe' })).resolves.toMatchObject({ id: 'person-1', firstName: 'Jane' }); expect(spies.peopleUpdate).toHaveBeenCalledWith('person-1', { firstName: 'Jane', lastName: 'Doe' }); expect(spies.peopleCreate).not.toHaveBeenCalled() })
  it('rejects profile updates when no person profile exists', async () => { spies.findPersonByUserId.mockResolvedValue(null); await expect(professionalService.updateProfile({ userId: 7, firstName: 'Jane', lastName: 'Doe' })).rejects.toThrow('Professional person profile not found.'); expect(spies.peopleCreate).not.toHaveBeenCalled(); expect(spies.peopleUpdate).not.toHaveBeenCalled() })
  it('blocks professional verification application without a person profile', async () => { spies.findPersonByUserId.mockResolvedValue(null); await expect(professionalService.applyForVerification({ userId: 7, registrationNumber: 'REG-1', prcId: 'PRC-1', ptrNumber: 'PTR-1' })).rejects.toThrow('Complete your person profile before applying for professional verification.') })
})

describe('professional credentials and events', () => {
  it('requires PRC ID and PTR when applying for verification', async () => { await expect(professionalService.applyForVerification({ userId: 'user-1', prcId: '', ptrNumber: 'PTR-1' })).rejects.toThrow('prcId is required.'); await expect(professionalService.applyForVerification({ userId: 'user-1', prcId: 'PRC-1', ptrNumber: '' })).rejects.toThrow('ptrNumber is required.') })
  it('persists normalized PRC and PTR credentials and auto-generates registration number', async () => { spies.findPersonByUserId.mockResolvedValue({ id: 'person-1' }); spies.findByPersonId.mockResolvedValue(null); spies.create.mockResolvedValue({ id: 'professional-1', status: 'PENDING_VERIFICATION' }); await professionalService.applyForVerification({ userId: 'user-1', registrationNumber: ' REG-1 ', prcId: ' PRC-1 ', ptrNumber: ' PTR-1 ' }); expect(spies.create).toHaveBeenCalledWith(expect.objectContaining({ personId: 'person-1', userId: 'user-1', prcId: 'PRC-1', ptrNumber: 'PTR-1' })); expect(spies.create.mock.calls[0][0].registrationNumber).toMatch(/^PRO-\d{8}-[0-9A-F]{8}$/) })
  it('allows the professional to retrieve their verification record', async () => { spies.findByUserId.mockResolvedValue({ id: 'professional-1', status: 'VERIFIED', prcId: 'PRC-1', ptrNumber: 'PTR-1' }); await expect(professionalService.getMine({ userId: 'user-1' })).resolves.toMatchObject({ status: 'VERIFIED', prcId: 'PRC-1', ptrNumber: 'PTR-1' }) })
  it('requires a reason when the Receiving Officer declines professional verification', async () => { spies.findById.mockResolvedValue({ id: 'professional-1', status: 'PENDING_VERIFICATION' }); await expect(professionalService.decideVerification({ id: 'professional-1', actorId: 'officer-1', decision: 'DECLINED' })).rejects.toThrow('reason is required') })
  it('includes PRC and PTR credentials in the verification decision event', async () => { spies.findById.mockResolvedValue({ id: 'professional-1', personId: 'person-1', userId: 'professional-user-1', status: 'PENDING_VERIFICATION', registrationNumber: 'REG-1', prcId: 'PRC-1', ptrNumber: 'PTR-1' }); spies.update.mockResolvedValue({ id: 'professional-1', status: 'VERIFIED' }); spies.addDecision.mockResolvedValue({ id: 'decision-1' }); spies.findPersonById.mockResolvedValue({ userId: 'professional-user-1', email: 'professional@example.com' }); await professionalService.decideVerification({ id: 'professional-1', actorId: 'officer-1', decision: 'ACCEPTED' }); expect(spies.publish).toHaveBeenCalledWith(expect.objectContaining({ event: 'obo.professional.verification.decided', context: expect.objectContaining({ prcId: 'PRC-1', ptrNumber: 'PTR-1' }) })) })
})

describe('professional submission snapshots', () => {
  const professional = { id: '00000000-0000-4000-8000-000000000001', registrationNumber: 'REG-123', prcId: 'PRC-123', ptrNumber: 'PTR-123', professionalRole: 'ARCHITECT', status: 'VERIFIED', person: { firstName: 'John', middleName: 'Q', lastName: 'Doe', suffix: null, isActive: true } }
  beforeEach(() => { spies.evaluateCondition.mockReturnValue(true); spies.getForReference.mockResolvedValue(professional) })
  it('captures the professional identity and credentials by form field', async () => { const formVersion = { fields: [{ key: 'architect', label: 'Architect', type: 'reference', required: true, visibility: null, config: { referenceType: 'obo_professional', professionalRole: 'ARCHITECT', multiple: false } }] }; await expect(referenceService.buildProfessionalSnapshots({ formVersion, formValues: { architect: professional.id } })).resolves.toEqual({ architect: { professionalId: professional.id, name: 'John Q Doe', registrationNumber: 'REG-123', prcId: 'PRC-123', ptrNumber: 'PTR-123', role: 'ARCHITECT' } }) })
  it('captures multiple selected professionals in field order', async () => { const second = { ...professional, id: '00000000-0000-4000-8000-000000000002', registrationNumber: 'REG-456', person: { ...professional.person, firstName: 'Jane', middleName: null, lastName: 'Smith' } }; spies.getForReference.mockResolvedValueOnce(professional).mockResolvedValueOnce(second); const formVersion = { fields: [{ key: 'architects', label: 'Architects', type: 'reference', required: true, visibility: null, config: { referenceType: 'obo_professional', professionalRole: 'ARCHITECT', multiple: true } }] }; await expect(referenceService.buildProfessionalSnapshots({ formVersion, formValues: { architects: [professional.id, second.id] } })).resolves.toEqual({ architects: [expect.objectContaining({ professionalId: professional.id, name: 'John Q Doe' }), expect.objectContaining({ professionalId: second.id, name: 'Jane Smith', registrationNumber: 'REG-456' })] }) })
  it('does not snapshot hidden or empty professional fields', async () => { spies.evaluateCondition.mockReturnValue(false); const formVersion = { fields: [{ key: 'architect', label: 'Architect', type: 'reference', required: false, visibility: { field: 'projectType', operator: 'equals', value: 'BUILDING' }, config: { referenceType: 'obo_professional', professionalRole: 'ARCHITECT', multiple: false } }] }; await expect(referenceService.buildProfessionalSnapshots({ formVersion, formValues: {} })).resolves.toEqual({}); expect(spies.getForReference).not.toHaveBeenCalled() })
})

describe('professional relationship migration contract', () => {
  const migrationPath = new URL('../../../prisma/migrations/20260908130000_remove_obo_application_professional/migration.sql', import.meta.url)
  const schemaPath = new URL('../../../prisma/modules/obo/permit-applications.prisma', import.meta.url)
  it('preserves legacy professional data before dropping the relationship', async () => { const sql = await readFile(migrationPath, 'utf8'); expect(sql).toContain('jsonb_build_object('); expect(sql).toContain("'_legacyProfessional'"); expect(sql).toContain('p."id"'); expect(sql).toContain('p."registrationNumber"'); expect(sql).toContain('p."prcId"'); expect(sql).toContain('p."ptrNumber"'); expect(sql).toContain('p."professionalRole"'); expect(sql.indexOf('jsonb_build_object(')).toBeLessThan(sql.indexOf('DROP COLUMN IF EXISTS "professionalId"')) })
  it('drops the legacy index, foreign key, and column without creating a join table', async () => { const sql = await readFile(migrationPath, 'utf8'); expect(sql).toContain('DROP INDEX IF EXISTS "OboPermitApplication_professionalId_createdAt_idx"'); expect(sql).toContain('DROP CONSTRAINT IF EXISTS "OboPermitApplication_professionalId_fkey"'); expect(sql).toContain('DROP COLUMN IF EXISTS "professionalId"'); expect(sql).not.toContain('CREATE TABLE "OboPermitApplicationProfessional"'); expect(sql).not.toContain('CREATE TABLE "ApplicationProfessional"') })
  it('keeps the Prisma application model free of a professional relationship', async () => { const schema = await readFile(schemaPath, 'utf8'); expect(schema).not.toMatch(/^\s*professionalId\s+/m); expect(schema).not.toMatch(/^\s*professional\s+OboProfessional/m); expect(schema).toMatch(/^\s*formValues\s+Json\s*$/m); expect(schema).toMatch(/^\s*professionalSnapshots\s+Json\?\s*$/m) })
})

describe('professional seed architecture', () => {
  const apiRoot = path.resolve(fileURLToPath(new URL('../../..', import.meta.url))); const seedRoot = path.join(apiRoot, 'scripts', 'seed'); const readSeed = (name) => readFile(path.join(seedRoot, name), 'utf8')
  it('seeds a verified professional with an explicit professional role', async () => { const content = await readSeed('obo-development.js'); expect(content).toContain("professionalRole: 'ARCHITECT'"); expect(content).toContain("status: 'VERIFIED'"); expect(content).toContain('professionalRole: OBO_DEVELOPMENT_FIXTURE.professionalRole') })
  it('stores the development professional selection in formValues', async () => { const content = await readSeed('obo-development.js'); expect(content).toContain("professionalFieldKey: 'architect'"); expect(content).toContain("type !== 'reference'"); expect(content).toContain("referenceType !== 'obo_professional'"); expect(content).toContain('[OBO_DEVELOPMENT_FIXTURE.professionalFieldKey]: professional.id'); expect(content).toContain('professionalSnapshots') })
  it('does not retain the removed application-level professional relation in the active seed', async () => { const content = await readSeed('obo-development.js'); const applicationUpsertStart = content.indexOf('const application = await prisma.oboPermitApplication.upsert('); const applicationUpsertEnd = content.indexOf('\n  await prisma.workflowInstance.update(', applicationUpsertStart); expect(applicationUpsertStart).toBeGreaterThanOrEqual(0); expect(applicationUpsertEnd).toBeGreaterThan(applicationUpsertStart); const applicationUpsert = content.slice(applicationUpsertStart, applicationUpsertEnd); expect(applicationUpsert).not.toContain('professionalId:'); expect(applicationUpsert).not.toContain('professionalId,'); expect(applicationUpsert).toContain('professionalSnapshots'); expect(applicationUpsert).toContain('formVersionId: formVersion.id'); expect(applicationUpsert).toContain('formValues,') })
  it('assigns roles to professional verification fixtures', async () => { const content = await readSeed('obo-professional-verification.js'); expect(content).toContain("professionalRole: 'ARCHITECT'"); expect(content).toContain("professionalRole: 'CIVIL_ENGINEER'"); expect(content).toContain('professionalRole: fixture.professionalRole') })
  it('uses the form-owned development seed module from db-seed', async () => { const content = await readFile(path.join(apiRoot, 'scripts', 'db-seed.js'), 'utf8'); expect(content).toContain("from './seed/obo-development.js'"); expect(content).not.toContain("from './seed/obo.js'") })
})
